### Matthew Riddell 
### D00245674
### MSc in Data Analytics
### Dissertation
### Data Prepartation Jupyter Notebook


In this part I will conduct data preparation, merging and cleaning of the datasets aswell as some feature extraction

This is so that the data is perfect for proper data analysis 

First I load and combine all the eci petitions into a single dataset with a new petition ID to differentiate the signature data per each petition 

I load the worldstat dataset

I remove the total signatures row from each petition

Remove sponsor and meta data rows from each petition

I remove commas and string symbols from the numerical columns in the eci dataset and convert them into proper numerical objects

I standardise the country names to match those in the Worldstat dataset

In the Worldstat dataset I select relevant columns and create a new dataframe

In the dataframe I rename the selected columns to be more legible 

Then I check for missing values across the selected columns

Checked for nonsense values and convert any into NaN 

I check for missing values again now that the nonsense values have been converted to NaN

I remove commas and string symbols from the numerical columns in the eci dataset and convert them into proper numerical objects

Conducted outlier detection using IQR method

Then I merge the selected columns with the ECI dataset using Country name 

Merged dataset is previewed and checked for missing values, In this case all of the missing / nonsense values were from countries that are outside of the EU

Just in case I put checks of missing value dropping while also checking the dataset size before and after

Checked for duplicate values: none were found

Lastly I created new features: Signatures per Capita, GDP per Capita, Threshold Ratio, Threshold per Capita

Added Petition name field

Final checks and previews of the data

Export final prepared dataset to new CSV file





### Link to each Dataset:

### ECI Petitions:
#### 2024

- ECI 01: https://citizens-initiative.europa.eu/initiatives/details/2024/000001_en Ban on conversion practices in the European Union
- ECI 02: https://citizens-initiative.europa.eu/initiatives/details/2024/000002_en European Citizens' Initiative in Defence of Agriculture and Rural Economy in Europe
- ECI 03: https://citizens-initiative.europa.eu/initiatives/details/2024/000004_en My Voice, My Choice: For Safe And Accessible Abortion
- ECI 04: https://citizens-initiative.europa.eu/initiatives/details/2024/000006_en Air-Quotas
- ECI 05: https://citizens-initiative.europa.eu/initiatives/details/2024/000007_en Stop Destroying Videogames
- ECI 06: https://citizens-initiative.europa.eu/initiatives/details/2024/000008_en Stop Cruelty Stop Slaughter
- ECI 07: https://citizens-initiative.europa.eu/initiatives/details/2024/000009_en STOP FAKE FOOD: ORIGIN ON LABEL
- ECI 08: https://citizens-initiative.europa.eu/initiatives/details/2024/000010_en ECI for a Water-Smart and Resilient Europe
- ECI 09: https://citizens-initiative.europa.eu/initiatives/details/2024/000011_en PsychedeliCare

#### 2023

- ECI 10: https://citizens-initiative.europa.eu/initiatives/details/2023/000001_en Stop torture and inhuman treatment at Europe’s borders
- ECI 11: https://citizens-initiative.europa.eu/initiatives/details/2023/000002_en Ensuring a dignified reception of migrants in Europe
- ECI 12: https://citizens-initiative.europa.eu/initiatives/details/2023/000003_en End The Horse Slaughter Age
- ECI 13: https://citizens-initiative.europa.eu/initiatives/details/2023/000004_en Connecting all European capitals and people through a high-speed train network
- ECI 14: https://citizens-initiative.europa.eu/initiatives/details/2023/000005_en Effective implementation of the concept of judicial precedent in EU countries
- ECI 15: https://citizens-initiative.europa.eu/initiatives/details/2023/000006_en Taxing great wealth to finance the ecological and social transition
- ECI 16: https://citizens-initiative.europa.eu/initiatives/details/2023/000007_en Preservation and development of Ukrainian culture, education, language, and traditions in EU states
- ECI 17: https://citizens-initiative.europa.eu/initiatives/details/2023/000008_en EU Live Bus Stop Info
- ECI 18: https://citizens-initiative.europa.eu/initiatives/details/2023/000009_en Trust and Freedom
- ECI 19: https://citizens-initiative.europa.eu/initiatives/details/2023/000011_en Creation of a European Environment Authority

#### 2022

- ECI 20: https://citizens-initiative.europa.eu/initiatives/details/2022/000001_en Win It On The Pitch 
- ECI 21: https://citizens-initiative.europa.eu/initiatives/details/2022/000002_en Fur Free Europe
- ECI 22: https://citizens-initiative.europa.eu/initiatives/details/2022/000003_en End The Slaughter Age
- ECI 23: https://citizens-initiative.europa.eu/initiatives/details/2022/000004_en Good Clothes, Fair Pay
- ECI 24: https://citizens-initiative.europa.eu/initiatives/details/2022/000007_en Protect the EU’s Rural Heritage, Food Security and Supply
- ECI 25: https://citizens-initiative.europa.eu/initiatives/details/2022/000008_en Focus on Specific Learning Disabilities on EU Level
- ECI 26: https://citizens-initiative.europa.eu/initiatives/details/2022/000009_en European Citizens’ Initiative for VEGAN MEAL
- ECI 27: https://citizens-initiative.europa.eu/initiatives/details/2022/000010_en European Day of "Whatever it Takes" 

### Worldstat Kaggle Dataset
https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

### 2023 Global Development and Prosperity Index 
https://www.kaggle.com/datasets/tarktunataalt/2023-global-country-development-and-prosperity-index

### Media Literacy Index Dataset 2023
https://osis.bg/wp-content/uploads/2023/06/MLI-report-in-English-22.06.pdf

https://osis.bg/?p=4450&lang=en

### Mahara Portfolio:
https://mahara.dkit.ie/view/view.php?t=f816cb6da6dd833aaa2f

### Github Repository:
https://github.com/Matthew-Riddell/MSc-Dissertation

In [82]:
import pandas as pd 
import numpy as np
import os

#### File path and file loading

In [83]:
file_path = r"C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Dissertation/MSc-Dissertation/data/Unprepared Datasets/"

# world stats datasets
file_name_worldstat = "world-data-2023.csv"

# eci datasets
eci_files = [
    "eci_table_01.csv",
    "eci_table_02.csv",
    "eci_table_03.csv",
    "eci_table_04.csv",
    "eci_table_05.csv",
    "eci_table_06.csv",
    "eci_table_07.csv",
    "eci_table_08.csv",
    "eci_table_09.csv",
    "eci_table_10.csv",
    "eci_table_11.csv",
    "eci_table_12.csv",
    "eci_table_13.csv",
    "eci_table_14.csv",
    "eci_table_15.csv",
    "eci_table_16.csv",
    "eci_table_17.csv",
    "eci_table_18.csv",
    "eci_table_19.csv",
    "eci_table_20.csv",
    "eci_table_21.csv",
    "eci_table_22.csv",
    "eci_table_23.csv",
    "eci_table_24.csv",
    "eci_table_25.csv",
    "eci_table_26.csv",
    "eci_table_27.csv"
]

### Loading World stats dataset

In [84]:
file_path_worldstat = os.path.join(file_path, file_name_worldstat)
world_data = pd.read_csv(file_path_worldstat)

### Loading ECI datasets into one dataset
This combines the data from all selected petitions into one dataset while creating a petition id to differentiate

In [85]:
eci_dfs = []
petition_totals = []

for file_name in eci_files:
    
    file_path_eci = os.path.join(file_path, file_name)
    
    df = pd.read_csv(file_path_eci)
    
    # Add id for each petition
    df["Petition_ID"] = file_name.replace(".csv", "")
    
    eci_dfs.append(df)

# Combine into one dataset
eci_data = pd.concat(eci_dfs, ignore_index=True)

#### Display first 5 rows

In [86]:
eci_data.head(40)

                        Country Signatures Threshold Percentage   Petition_ID
0                       Austria     10,724    13,395     80.06%  eci_table_01
1                       Belgium     47,459    14,805    320.56%  eci_table_01
2                      Bulgaria      2,386    11,985     19.91%  eci_table_01
3                       Croatia      8,574     8,460    101.35%  eci_table_01
4                        Cyprus        696     4,230     16.45%  eci_table_01
5                       Czechia      3,774    14,805     25.49%  eci_table_01
6                       Denmark      8,587     9,870     87.00%  eci_table_01
7                       Estonia      1,519     4,935     30.78%  eci_table_01
8                       Finland     23,618     9,870    239.29%  eci_table_01
9                        France    580,568    55,695  1,042.41%  eci_table_01
10                      Germany     92,739    67,680    137.03%  eci_table_01
11                       Greece      4,127    14,805     27.88%  eci_table_01
12                      Hungary      3,195    14,805     21.58%  eci_table_01
13                      Ireland     18,503     9,165    201.89%  eci_table_01
14                        Italy     60,701    53,580    113.29%  eci_table_01
15                       Latvia      1,103     5,640     19.56%  eci_table_01
16                    Lithuania      1,973     7,755     25.44%  eci_table_01
17                   Luxembourg      2,091     4,230     49.43%  eci_table_01
18                        Malta        861     4,230     20.35%  eci_table_01
19                  Netherlands     38,112    20,445    186.41%  eci_table_01
20                       Poland      9,039    36,660     24.66%  eci_table_01
21                     Portugal      9,025    14,805     60.96%  eci_table_01
22                      Romania      9,932    23,265     42.69%  eci_table_01
23                     Slovakia      2,671     9,870     27.06%  eci_table_01
24                     Slovenia      6,400     5,640    113.48%  eci_table_01
25                        Spain    162,018    41,595    389.51%  eci_table_01
26                       Sweden     17,668    14,805    119.34%  eci_table_01
27  Total number of signatories  1,128,063       NaN        NaN  eci_table_01
28                      Austria        109    13,395      0.81%  eci_table_02
29                      Belgium        160    14,805      1.08%  eci_table_02
30                     Bulgaria         47    11,985      0.39%  eci_table_02
31                      Croatia         76     8,460      0.90%  eci_table_02
32                       Cyprus         27     4,230      0.64%  eci_table_02
33                      Czechia         39    14,805      0.26%  eci_table_02
34                      Denmark         29     9,870      0.29%  eci_table_02
35                      Estonia         18     4,935      0.36%  eci_table_02
36                      Finland        102     9,870      1.03%  eci_table_02
37                       France        361    55,695      0.65%  eci_table_02
38                      Germany        302    67,680      0.45%  eci_table_02
39                       Greece        120    14,805      0.81%  eci_table_02

In [87]:
world_data.head(5)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887

In [88]:
print("First 5 rows of the ECI data:")
print(eci_data.head())

First 5 rows of the ECI data:
    Country Signatures Threshold Percentage   Petition_ID
0   Austria     10,724    13,395     80.06%  eci_table_01
1   Belgium     47,459    14,805    320.56%  eci_table_01
2  Bulgaria      2,386    11,985     19.91%  eci_table_01
3   Croatia      8,574     8,460    101.35%  eci_table_01
4    Cyprus        696     4,230     16.45%  eci_table_01

In [89]:
print("First 5 rows of the World Stat dataset:")
print(world_data.head())

First 5 rows of the World Stat dataset:
       Country Density\n(P/Km2) Abbreviation Agricultural Land( %)  \
0  Afghanistan               60           AF                58.10%
1      Albania              105           AL                43.10%
2      Algeria               18           DZ                17.40%
3      Andorra              164           AD                40.00%
4       Angola               26           AO                47.50%

  Land Area(Km2) Armed Forces size  Birth Rate  Calling Code  \
0        652,230           323,000       32.49          93.0
1         28,748             9,000       11.78         355.0
2      2,381,741           317,000       24.28         213.0
3            468               NaN        7.20         376.0
4      1,246,700           117,000       40.73         244.0

  Capital/Major City Co2-Emissions  ... Out of pocket health expenditure  \
0              Kabul         8,672  ...                           78.40%
1             Tirana         4,536  ...                           56.90%
2            Algiers       150,006  ...                           28.10%
3   Andorra la Vella           469  ...                           36.40%
4             Luanda        34,693  ...                           33.40%

  Physicians per thousand  Population  \
0                    0.28  38,041,754
1                    1.20   2,854,191
2                    1.72  43,053,054
3                    3.33      77,142
4                    0.21  31,825,295

   Population: Labor force participation (%) Tax revenue (%) Total tax rate  \
0                                     48.90%           9.30%         71.40%
1                                     55.70%          18.60%         36.60%
2                                     41.20%          37.20%         66.10%
3                                        NaN             NaN            NaN
4                                     77.50%           9.20%         49.10%

  Unemployment rate Urban_population   Latitude  Longitude
0            11.12%        9,797,273  33.939110  67.709953
1            12.33%        1,747,593  41.153332  20.168331
2            11.70%       31,510,100  28.033886   1.659626
3               NaN           67,873  42.506285   1.521801
4             6.89%       21,061,025 -11.202692  17.873887

[5 rows x 35 columns]

#### Check basic information about the dataset

In [90]:
print("Information about the ECI dataset:")
print(eci_data.info())

Information about the ECI dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Country      756 non-null    object
 1   Signatures   756 non-null    object
 2   Threshold    729 non-null    object
 3   Percentage   729 non-null    object
 4   Petition_ID  756 non-null    object
dtypes: object(5)
memory usage: 29.7+ KB
None

In [91]:
print("Information about the World Data dataset:")
print(world_data.info())

Information about the World Data dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Country                                    195 non-null    object
 1   Density
(P/Km2)                            195 non-null    object
 2   Abbreviation                               188 non-null    object
 3   Agricultural Land( %)                      188 non-null    object
 4   Land Area(Km2)                             194 non-null    object
 5   Armed Forces size                          171 non-null    object
 6   Birth Rate                                 189 non-null    float64
 7   Calling Code                               194 non-null    float64
 8   Capital/Major City                         192 non-null    object
 9   Co2-Emissions                              188 non-null    object
 10  CPI                                        178 non-null    object
 11  CPI Change (%)                             179 non-null    object
 12  Currency-Code                              180 non-null    object
 13  Fertility Rate                             188 non-null    float64
 14  Forested Area (%)                          188 non-null    object
 15  Gasoline Price                             175 non-null    object
 16  GDP                                        193 non-null    object
 17  Gross primary education enrollment (%)     188 non-null    object
 18  Gross tertiary education enrollment (%)    183 non-null    object
 19  Infant mortality                           189 non-null    float64
 20  Largest city                               189 non-null    object
 21  Life expectancy                            187 non-null    float64
 22  Maternal mortality ratio                   181 non-null    float64
 23  Minimum wage                               150 non-null    object
 24  Official language                          190 non-null    object
 25  Out of pocket health expenditure           188 non-null    object
 26  Physicians per thousand                    188 non-null    float64
 27  Population                                 194 non-null    object
 28  Population: Labor force participation (%)  176 non-null    object
 29  Tax revenue (%)                            169 non-null    object
 30  Total tax rate                             183 non-null    object
 31  Unemployment rate                          176 non-null    object
 32  Urban_population                           190 non-null    object
 33  Latitude                                   194 non-null    float64
 34  Longitude                                  194 non-null    float64
dtypes: float64(9), object(26)
memory usage: 53.4+ KB
None

#### Display column names

In [92]:
print("Original column names:")
print(eci_data.columns)

Original column names:
Index(['Country', 'Signatures', 'Threshold', 'Percentage', 'Petition_ID'], dtype='object')

In [93]:
print("Original column names:")
print(world_data.columns)

Original column names:
Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price', 'GDP', 'Gross primary education enrollment (%)',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Largest city', 'Life expectancy', 'Maternal mortality ratio',
       'Minimum wage', 'Official language', 'Out of pocket health expenditure',
       'Physicians per thousand', 'Population',
       'Population: Labor force participation (%)', 'Tax revenue (%)',
       'Total tax rate', 'Unemployment rate', 'Urban_population', 'Latitude',
       'Longitude'],
      dtype='object')

## Data Cleaning

### Cleaning Petition Datasets

### Remove total signatures rows from the dataset

checks every row to see if there is a value contained in the country column, total signatures row doesnt contain a value there so it is NaN 

it then excludes it from the dataset

In [94]:
eci_data = eci_data[
    ~eci_data["Country"].str.contains(
        "Total number of signatories",
        case=False,
        na=False
    )
]

### Remove Sponsor and Metadata rows

In [95]:
eci_data = eci_data[
    ~eci_data["Country"].str.contains(
        "Name of sponsor|Date|Description",
        case=False,
        na=False
    )
]

### Removing commas from numeric columns

#### Signatures column

In [96]:
eci_data["Signatures"] = (
    eci_data["Signatures"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

#### Threshold Column

In [97]:
eci_data["Threshold"] = (
    eci_data["Threshold"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

#### Percentage Column

In [98]:
eci_data["Percentage"] = (
    eci_data["Percentage"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

### Remove Percentage Sign from Percentage column

In [99]:
eci_data["Percentage"] = (
    eci_data["Percentage"]
    .astype(str)
    .str.replace("%", "", regex=False)
)

### Convert columns into numeric

#### Signatures column

In [100]:
eci_data["Signatures"] = pd.to_numeric(
    eci_data["Signatures"],
    errors="coerce"
)

#### Threshold Column

In [101]:
eci_data["Threshold"] = pd.to_numeric(
    eci_data["Threshold"],
    errors="coerce"
)

#### Percentage Column

In [102]:
eci_data["Percentage"] = pd.to_numeric(
    eci_data["Percentage"],
    errors="coerce"
)

### Checking the data after cleaning the columns and converting into numericals

In [103]:
eci_data.head(30)

        Country  Signatures  Threshold  Percentage   Petition_ID
0       Austria       10724      13395       80.06  eci_table_01
1       Belgium       47459      14805      320.56  eci_table_01
2      Bulgaria        2386      11985       19.91  eci_table_01
3       Croatia        8574       8460      101.35  eci_table_01
4        Cyprus         696       4230       16.45  eci_table_01
5       Czechia        3774      14805       25.49  eci_table_01
6       Denmark        8587       9870       87.00  eci_table_01
7       Estonia        1519       4935       30.78  eci_table_01
8       Finland       23618       9870      239.29  eci_table_01
9        France      580568      55695     1042.41  eci_table_01
10      Germany       92739      67680      137.03  eci_table_01
11       Greece        4127      14805       27.88  eci_table_01
12      Hungary        3195      14805       21.58  eci_table_01
13      Ireland       18503       9165      201.89  eci_table_01
14        Italy       60701      53580      113.29  eci_table_01
15       Latvia        1103       5640       19.56  eci_table_01
16    Lithuania        1973       7755       25.44  eci_table_01
17   Luxembourg        2091       4230       49.43  eci_table_01
18        Malta         861       4230       20.35  eci_table_01
19  Netherlands       38112      20445      186.41  eci_table_01
20       Poland        9039      36660       24.66  eci_table_01
21     Portugal        9025      14805       60.96  eci_table_01
22      Romania        9932      23265       42.69  eci_table_01
23     Slovakia        2671       9870       27.06  eci_table_01
24     Slovenia        6400       5640      113.48  eci_table_01
25        Spain      162018      41595      389.51  eci_table_01
26       Sweden       17668      14805      119.34  eci_table_01
28      Austria         109      13395        0.81  eci_table_02
29      Belgium         160      14805        1.08  eci_table_02
30     Bulgaria          47      11985        0.39  eci_table_02

### Standardise country names

this is so they match the country names in the world dataset

In [104]:
country_mapping = {
    "Czechia": "Czech Republic",
    "Ireland": "Republic of Ireland"
}

eci_data["Country"] = eci_data["Country"].replace(country_mapping)

### Checking the data after cleaning the columns and converting into numericals

In [105]:
eci_data.head(30)

                Country  Signatures  Threshold  Percentage   Petition_ID
0               Austria       10724      13395       80.06  eci_table_01
1               Belgium       47459      14805      320.56  eci_table_01
2              Bulgaria        2386      11985       19.91  eci_table_01
3               Croatia        8574       8460      101.35  eci_table_01
4                Cyprus         696       4230       16.45  eci_table_01
5        Czech Republic        3774      14805       25.49  eci_table_01
6               Denmark        8587       9870       87.00  eci_table_01
7               Estonia        1519       4935       30.78  eci_table_01
8               Finland       23618       9870      239.29  eci_table_01
9                France      580568      55695     1042.41  eci_table_01
10              Germany       92739      67680      137.03  eci_table_01
11               Greece        4127      14805       27.88  eci_table_01
12              Hungary        3195      14805       21.58  eci_table_01
13  Republic of Ireland       18503       9165      201.89  eci_table_01
14                Italy       60701      53580      113.29  eci_table_01
15               Latvia        1103       5640       19.56  eci_table_01
16            Lithuania        1973       7755       25.44  eci_table_01
17           Luxembourg        2091       4230       49.43  eci_table_01
18                Malta         861       4230       20.35  eci_table_01
19          Netherlands       38112      20445      186.41  eci_table_01
20               Poland        9039      36660       24.66  eci_table_01
21             Portugal        9025      14805       60.96  eci_table_01
22              Romania        9932      23265       42.69  eci_table_01
23             Slovakia        2671       9870       27.06  eci_table_01
24             Slovenia        6400       5640      113.48  eci_table_01
25                Spain      162018      41595      389.51  eci_table_01
26               Sweden       17668      14805      119.34  eci_table_01
28              Austria         109      13395        0.81  eci_table_02
29              Belgium         160      14805        1.08  eci_table_02
30             Bulgaria          47      11985        0.39  eci_table_02

### Cleaning World Data Dataset

In [106]:
print("Original column names:")
print(world_data.columns)

Original column names:
Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price', 'GDP', 'Gross primary education enrollment (%)',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Largest city', 'Life expectancy', 'Maternal mortality ratio',
       'Minimum wage', 'Official language', 'Out of pocket health expenditure',
       'Physicians per thousand', 'Population',
       'Population: Labor force participation (%)', 'Tax revenue (%)',
       'Total tax rate', 'Unemployment rate', 'Urban_population', 'Latitude',
       'Longitude'],
      dtype='object')

### Selecting relevant columns

In [107]:
selected_columns = [
    "Country",
    "Population",
    "GDP",
    "Density\n(P/Km2)",
    "Unemployment rate",
    "Gross tertiary education enrollment (%)",
    "Life expectancy",
    "Urban_population",
    "Population: Labor force participation (%)"
]

### New dataframe with selected columns

In [108]:
world_selected = world_data[selected_columns]

### Previewing the data

In [109]:
world_selected.head()

,Country,Population,GDP,Density\n(P/Km2),Unemployment rate,Gross tertiary education enrollment (%),Life expectancy,Urban_population,Population: Labor force participation (%)
0,Afghanistan,"38,041,754","$19,101,353,833",60,11.12%,9.70%,64.5,"9,797,273",48.90%
1,Albania,"2,854,191","$15,278,077,447",105,12.33%,55.00%,78.5,"1,747,593",55.70%
2,Algeria,"43,053,054","$169,988,236,398",18,11.70%,51.40%,76.7,"31,510,100",41.20%
3,Andorra,"77,142","$3,154,057,987",164,NaN,NaN,NaN,"67,873",NaN
4,Angola,"31,825,295","$94,635,415,870",26,6.89%,9.30%,60.8,"21,061,025",77.50%

In [110]:
print("Information about the dataset:")
print(world_selected.info())

Information about the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 9 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Country                                    195 non-null    object
 1   Population                                 194 non-null    object
 2   GDP                                        193 non-null    object
 3   Density
(P/Km2)                            195 non-null    object
 4   Unemployment rate                          176 non-null    object
 5   Gross tertiary education enrollment (%)    183 non-null    object
 6   Life expectancy                            187 non-null    float64
 7   Urban_population                           190 non-null    object
 8   Population: Labor force participation (%)  176 non-null    object
dtypes: float64(1), object(8)
memory usage: 13.8+ KB
None

### Displaying column names

In [111]:
print("Original column names:")
print(world_selected.columns)

Original column names:
Index(['Country', 'Population', 'GDP', 'Density\n(P/Km2)', 'Unemployment rate',
       'Gross tertiary education enrollment (%)', 'Life expectancy',
       'Urban_population', 'Population: Labor force participation (%)'],
      dtype='object')

### Renaming columns

In [112]:
world_selected = world_selected.rename(columns={
    "Density\n(P/Km2)": "Population_Density",
    "Unemployment rate": "Unemployment_Rate",
    "Gross tertiary education enrollment (%)": "Tertiary_Enrollment",
    "Life expectancy": "Life_Expectancy",
    "Urban_population": "Urban_Population",
    "Population: Labor force participation (%)": "Labor_Participation"
})

### Display Missing values in the dataset

In [113]:
print("Number of missing values in each column:")
print(world_selected.isna().sum())

Number of missing values in each column:
Country                 0
Population              1
GDP                     2
Population_Density      0
Unemployment_Rate      19
Tertiary_Enrollment    12
Life_Expectancy         8
Urban_Population        5
Labor_Participation    19
dtype: int64

### Total missing values in the dataset

In [114]:
total_missing = world_selected.isna().sum().sum()
print("Total missing values in the dataset:", total_missing)

Total missing values in the dataset: 66

### Nonsense values

In [115]:
nonsense_values = ["?", "error", "missing", "Missing", "NaN", "nan", "N/A", "n/a", "--", " "]

### Checking for nonense values

In [116]:
print("Checking for nonsense values:")
for col in world_selected.columns:
    count = world_selected[col].isin(nonsense_values).sum() 
    if count > 0:
        print(col, "has", count, "nonsense values")
    else:
        print("No nonsense values found!")

Checking for nonsense values:
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!

### Converting nonsense values to NaN

In [117]:
world_selected = world_selected.replace(nonsense_values, np.nan)

### Viewing total missing values again

In [118]:
print("Number of missing values after cleaning nonsense values:")
print(world_selected.isna().sum())

Number of missing values after cleaning nonsense values:
Country                 0
Population              1
GDP                     2
Population_Density      0
Unemployment_Rate      19
Tertiary_Enrollment    12
Life_Expectancy         8
Urban_Population        5
Labor_Participation    19
dtype: int64

### Remove comma from columns

Population

In [119]:
world_selected["Population"] = (
    world_selected["Population"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

GDP

In [120]:
world_selected["GDP"] = (
    world_selected["GDP"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

Population Density

In [121]:
world_selected["Population_Density"] = (
    world_selected["Population_Density"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

Unemployment Rate

In [122]:
world_selected["Unemployment_Rate"] = (
    world_selected["Unemployment_Rate"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

Tertiary Enrollment

In [123]:
world_selected["Tertiary_Enrollment"] = (
    world_selected["Tertiary_Enrollment"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

Life Expectancy

In [124]:
world_selected["Life_Expectancy"] = (
    world_selected["Life_Expectancy"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

Urban Population

In [125]:
world_selected["Urban_Population"] = (
    world_selected["Urban_Population"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

Labor Participation

In [126]:
world_selected["Labor_Participation"] = (
    world_selected["Labor_Participation"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

### Remove dollar sign

GDP

In [127]:
world_selected["GDP"] = (
    world_selected["GDP"]
    .astype(str)
    .str.replace("$", "", regex=False)
)

### Remove percentage marker

Unemployment Rate

In [128]:
world_selected["Unemployment_Rate"] = (
    world_selected["Unemployment_Rate"]
    .astype(str)
    .str.replace("%", "", regex=False)
)

Tertiary Enrollment

In [129]:
world_selected["Tertiary_Enrollment"] = (
    world_selected["Tertiary_Enrollment"]
    .astype(str)
    .str.replace("%", "", regex=False)
)

Labor Participation

In [130]:
world_selected["Labor_Participation"] = (
    world_selected["Labor_Participation"]
    .astype(str)
    .str.replace("%", "", regex=False)
)

### Convert to numeric

Population

In [131]:
world_selected["Population"] = pd.to_numeric(
    world_selected["Population"],
    errors="coerce"
)

GDP

In [132]:
world_selected["GDP"] = pd.to_numeric(
    world_selected["GDP"],
    errors="coerce"
)

Population Density

In [133]:
world_selected["Population_Density"] = pd.to_numeric(
    world_selected["Population_Density"],
    errors="coerce"
)

Unemployment Rate

In [134]:
world_selected["Unemployment_Rate"] = pd.to_numeric(
    world_selected["Unemployment_Rate"],
    errors="coerce"
)

Tertiary Enrollment

In [135]:
world_selected["Tertiary_Enrollment"] = pd.to_numeric(
    world_selected["Tertiary_Enrollment"],
    errors="coerce"
)

LIfe Expectancy

In [136]:
world_selected["Life_Expectancy"] = pd.to_numeric(
    world_selected["Life_Expectancy"],
    errors="coerce"
)

Urban Population

In [137]:
world_selected["Urban_Population"] = pd.to_numeric(
    world_selected["Urban_Population"],
    errors="coerce"
)

Labor Participation

In [138]:
world_selected["Labor_Participation"] = pd.to_numeric(
    world_selected["Labor_Participation"],
    errors="coerce"
)

### Numeric columns

In [139]:
numeric_columns = ['Population', 'GDP', 'Population_Density', 
                   'Unemployment_Rate', 'Tertiary_Enrollment', 'Life_Expectancy', 
                   'Urban_Population', 'Labor_Participation']

### Outlier detection

In [140]:
print("Detecting outliers using IQR method:\n")

for col in numeric_columns:
    if col in world_selected.columns:
        Q1 = world_selected[col].quantile(0.25) # https://www.w3schools.com/Python/pandas/ref_df_quantile.asp
        Q3 = world_selected[col].quantile(0.75) # https://www.w3schools.com/Python/pandas/ref_df_quantile.asp
        IQR = Q3 - Q1
        lower_limit = Q1 - 1.5 * IQR
        upper_limit = Q3 + 1.5 * IQR
        
        outliers = world_selected[(world_selected[col] < lower_limit) | (world_selected[col] > upper_limit)]
        print(col, "has", outliers.shape[0], "outliers")

Detecting outliers using IQR method:

Population has 20 outliers
GDP has 21 outliers
Population_Density has 17 outliers
Unemployment_Rate has 6 outliers
Tertiary_Enrollment has 0 outliers
Life_Expectancy has 0 outliers
Urban_Population has 25 outliers
Labor_Participation has 0 outliers

### Merging ECI dataset with World Data

merge based on country, dropping rows that dont include EU countries

In [141]:
merged_data = pd.merge(
    eci_data,
    world_selected,
    on="Country",
    how="left"
)

### Preview merged dataset

In [142]:
merged_data.head(20)

,Country,Signatures,Threshold,Percentage,Petition_ID,Population,GDP,Population_Density,Unemployment_Rate,Tertiary_Enrollment,Life_Expectancy,Urban_Population,Labor_Participation
0,Austria,10724,13395,80.06,eci_table_01,8877067.0,4.463147e+11,109,4.67,85.1,81.6,5194416.0,60.7
1,Belgium,47459,14805,320.56,eci_table_01,11484055.0,5.296067e+11,383,5.59,79.7,81.6,11259082.0,53.6
2,Bulgaria,2386,11985,19.91,eci_table_01,6975761.0,8.600000e+10,64,4.34,71.0,74.9,5256027.0,55.4
3,Croatia,8574,8460,101.35,eci_table_01,4067500.0,6.041555e+10,73,6.93,67.9,78.1,2328318.0,51.2
4,Cyprus,696,4230,16.45,eci_table_01,1198575.0,2.456465e+10,131,7.27,75.9,80.8,800708.0,63.1
5,Czech Republic,3774,14805,25.49,eci_table_01,10669709.0,2.464892e+11,139,1.93,64.1,79.0,7887156.0,60.6
6,Denmark,8587,9870,87.00,eci_table_01,5818553.0,3.480780e+11,137,4.91,80.6,81.0,5119978.0,62.2
7,Estonia,1519,4935,30.78,eci_table_01,1331824.0,3.138695e+10,31,5.11,69.6,78.2,916024.0,63.6
8,Finland,23618,9870,239.29,eci_table_01,5520314.0,2.687612e+11,18,6.59,88.2,81.7,4716888.0,59.1
9,France,580568,55695,1042.41,eci_table_01,67059887.0,2.715518e+12,119,8.43,65.6,82.5,54123364.0,55.1
10,Germany,92739,67680,137.03,eci_table_01,83132799.0,3.845630e+12,240,3.04,70.2,80.9,64324835.0,60.8
11,Greece,4127,14805,27.88,eci_table_01,10716322.0,2.098528e+11,81,17.24,136.6,81.3,8507474.0,51.8
12,Hungary,3195,14805,21.58,eci_table_01,9769949.0,1.609672e+11,107,3.40,48.5,75.8,6999582.0,56.5
13,Republic of Ireland,18503,9165,201.89,eci_table_01,5007069.0,3.886987e+11,72,4.93,77.8,82.3,3133123.0,62.1
14,Italy,60701,53580,113.29,eci_table_01,60297396.0,2.001244e+12,206,9.89,61.9,82.9,42651966.0,49.6
15,Latvia,1103,5640,19.56,eci_table_01,1912789.0,3.411720e+10,30,6.52,88.1,74.7,1304943.0,61.4
16,Lithuania,1973,7755,25.44,eci_table_01,2786844.0,5.421932e+10,43,6.35,72.4,75.7,1891013.0,61.6
17,Luxembourg,2091,4230,49.43,eci_table_01,645397.0,7.110492e+10,242,5.36,19.2,82.1,565488.0,59.3
18,Malta,861,4230,20.35,eci_table_01,502653.0,1.478616e+10,1380,3.47,54.3,82.3,475902.0,56.5
19,Netherlands,38112,20445,186.41,eci_table_01,17332850.0,9.090704e+11,508,3.20,85.0,81.8,15924729.0,63.6

### Check Missing Values

In [143]:
print("Number of missing values in each column:")
print(merged_data.isna().sum())

Number of missing values in each column:
Country                0
Signatures             0
Threshold              0
Percentage             0
Petition_ID            0
Population             0
GDP                    0
Population_Density     0
Unemployment_Rate      0
Tertiary_Enrollment    0
Life_Expectancy        0
Urban_Population       0
Labor_Participation    0
dtype: int64

### Total Missing Values

In [144]:
total_missing = merged_data.isna().sum().sum()
print("Total missing values in the dataset:", total_missing)

Total missing values in the dataset: 0

### Check for nonsense values again

In [145]:
print("Checking for nonsense values:")
for col in merged_data.columns:
    count = merged_data[col].isin(nonsense_values).sum() 
    if count > 0:
        print(col, "has", count, "nonsense values")
    else:
        print("No nonsense values found!")

Checking for nonsense values:
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!
No nonsense values found!

### Convert nonsense values to NaN

In [146]:
merged_data = merged_data.replace(nonsense_values, np.nan)

### Check for missing values again

In [147]:
print("Number of missing values after cleaning nonsense values:")
print(merged_data.isna().sum())

Number of missing values after cleaning nonsense values:
Country                0
Signatures             0
Threshold              0
Percentage             0
Petition_ID            0
Population             0
GDP                    0
Population_Density     0
Unemployment_Rate      0
Tertiary_Enrollment    0
Life_Expectancy        0
Urban_Population       0
Labor_Participation    0
dtype: int64

### Drop missing values
check how many rows are removed before dropping to ensure dataset size doesnt get reduced

In [148]:
before = merged_data.shape[0]

merged_data = merged_data.dropna()

after = merged_data.shape[0]

print(before - after)

0

### Check for missing values again

In [149]:
print("Number of missing values after dropping na rows:")
print(merged_data.isna().sum())

Number of missing values after dropping na rows:
Country                0
Signatures             0
Threshold              0
Percentage             0
Petition_ID            0
Population             0
GDP                    0
Population_Density     0
Unemployment_Rate      0
Tertiary_Enrollment    0
Life_Expectancy        0
Urban_Population       0
Labor_Participation    0
dtype: int64

### Check for Duplicates

In [150]:
print(
    "Duplicates:",
    merged_data.duplicated().sum()
)

Duplicates: 0

### Preview cleaned data

In [151]:
merged_data.head(20)

,Country,Signatures,Threshold,Percentage,Petition_ID,Population,GDP,Population_Density,Unemployment_Rate,Tertiary_Enrollment,Life_Expectancy,Urban_Population,Labor_Participation
0,Austria,10724,13395,80.06,eci_table_01,8877067.0,4.463147e+11,109,4.67,85.1,81.6,5194416.0,60.7
1,Belgium,47459,14805,320.56,eci_table_01,11484055.0,5.296067e+11,383,5.59,79.7,81.6,11259082.0,53.6
2,Bulgaria,2386,11985,19.91,eci_table_01,6975761.0,8.600000e+10,64,4.34,71.0,74.9,5256027.0,55.4
3,Croatia,8574,8460,101.35,eci_table_01,4067500.0,6.041555e+10,73,6.93,67.9,78.1,2328318.0,51.2
4,Cyprus,696,4230,16.45,eci_table_01,1198575.0,2.456465e+10,131,7.27,75.9,80.8,800708.0,63.1
5,Czech Republic,3774,14805,25.49,eci_table_01,10669709.0,2.464892e+11,139,1.93,64.1,79.0,7887156.0,60.6
6,Denmark,8587,9870,87.00,eci_table_01,5818553.0,3.480780e+11,137,4.91,80.6,81.0,5119978.0,62.2
7,Estonia,1519,4935,30.78,eci_table_01,1331824.0,3.138695e+10,31,5.11,69.6,78.2,916024.0,63.6
8,Finland,23618,9870,239.29,eci_table_01,5520314.0,2.687612e+11,18,6.59,88.2,81.7,4716888.0,59.1
9,France,580568,55695,1042.41,eci_table_01,67059887.0,2.715518e+12,119,8.43,65.6,82.5,54123364.0,55.1
10,Germany,92739,67680,137.03,eci_table_01,83132799.0,3.845630e+12,240,3.04,70.2,80.9,64324835.0,60.8
11,Greece,4127,14805,27.88,eci_table_01,10716322.0,2.098528e+11,81,17.24,136.6,81.3,8507474.0,51.8
12,Hungary,3195,14805,21.58,eci_table_01,9769949.0,1.609672e+11,107,3.40,48.5,75.8,6999582.0,56.5
13,Republic of Ireland,18503,9165,201.89,eci_table_01,5007069.0,3.886987e+11,72,4.93,77.8,82.3,3133123.0,62.1
14,Italy,60701,53580,113.29,eci_table_01,60297396.0,2.001244e+12,206,9.89,61.9,82.9,42651966.0,49.6
15,Latvia,1103,5640,19.56,eci_table_01,1912789.0,3.411720e+10,30,6.52,88.1,74.7,1304943.0,61.4
16,Lithuania,1973,7755,25.44,eci_table_01,2786844.0,5.421932e+10,43,6.35,72.4,75.7,1891013.0,61.6
17,Luxembourg,2091,4230,49.43,eci_table_01,645397.0,7.110492e+10,242,5.36,19.2,82.1,565488.0,59.3
18,Malta,861,4230,20.35,eci_table_01,502653.0,1.478616e+10,1380,3.47,54.3,82.3,475902.0,56.5
19,Netherlands,38112,20445,186.41,eci_table_01,17332850.0,9.090704e+11,508,3.20,85.0,81.8,15924729.0,63.6

In [152]:
print("Shape of the dataset after data cleaning and merging:", merged_data.shape)

Shape of the dataset after data cleaning and merging: (729, 13)

### Feature Extraction

#### Signatures per Capita field

In [153]:
merged_data["Signatures_Per_Capita"] = (
    merged_data["Signatures"] /
    merged_data["Population"]
)

#### GDP per Capita

In [154]:
merged_data["GDP_Per_Capita"] = (
    merged_data["GDP"] /
    merged_data["Population"]
)

#### Threshold Ratio

In [155]:
merged_data["Threshold_Ratio"] = (
    merged_data["Signatures"] /
    merged_data["Threshold"]
)

#### Threshold Per Capita

In [156]:
merged_data["Threshold_Per_Capita"] = (
    merged_data["Threshold"] /
    merged_data["Population"]
)

### Final checks

In [157]:
print("Final check on missing values:")
print(merged_data.isna().sum())

Final check on missing values:
Country                  0
Signatures               0
Threshold                0
Percentage               0
Petition_ID              0
Population               0
GDP                      0
Population_Density       0
Unemployment_Rate        0
Tertiary_Enrollment      0
Life_Expectancy          0
Urban_Population         0
Labor_Participation      0
Signatures_Per_Capita    0
GDP_Per_Capita           0
Threshold_Ratio          0
Threshold_Per_Capita     0
dtype: int64

### Petition Names

In [158]:
petition_names = {
    "eci_table_01": "Ban Conversion Practices",
    "eci_table_02": "Defence of Agriculture",
    "eci_table_03": "My Voice My Choice",
    "eci_table_04": "Air-Quotas",
    "eci_table_05": "Stop Destroying Videogames",
    "eci_table_06": "Stop Cruelty Stop Slaughter",
    "eci_table_07": "STOP FAKE FOOD: ORIGIN ON LABEL",
    "eci_table_08": "Water-Smart and Resilient Europe",
    "eci_table_09": "PsychedeliCare",
    "eci_table_10": "Stop torture and inhuman treatment at Europe’s borders",
    "eci_table_11": "Ensuring a dignified reception of migrants in Europe",
    "eci_table_12": "End The Horse Slaughter Age",
    "eci_table_13": "Connecting European capitals via high-speed train network",
    "eci_table_14": "Implementation of the concept of judicial precedent",
    "eci_table_15": "Taxing wealth to finance ecological social transition",
    "eci_table_16": "Development of Ukrainian culture",
    "eci_table_17": "EU Live Bus Stop Info",
    "eci_table_18": "Trust and Freedom",
    "eci_table_19": "Creation of a European Environment Authority",
    "eci_table_20": "Win It On The Pitch",
    "eci_table_21": "Fur Free Europe",
    "eci_table_22": "End The Slaughter Age",
    "eci_table_23": "Good Clothes, Fair Pay",
    "eci_table_24": "Protect EU Rural Heritage, Food Security and Supply",
    "eci_table_25": "Focus on Specific Learning Disabilities",
    "eci_table_26": "VEGAN MEAL",
    "eci_table_27": "European Day of Whatever it Takes"
}

In [159]:
merged_data["Petition_Name"] = (
    merged_data["Petition_ID"]
    .map(petition_names)
)

In [160]:
merged_data.head(20)

,Country,Signatures,Threshold,Percentage,Petition_ID,Population,GDP,Population_Density,Unemployment_Rate,Tertiary_Enrollment,Life_Expectancy,Urban_Population,Labor_Participation,Signatures_Per_Capita,GDP_Per_Capita,Threshold_Ratio,Threshold_Per_Capita,Petition_Name
0,Austria,10724,13395,80.06,eci_table_01,8877067.0,4.463147e+11,109,4.67,85.1,81.6,5194416.0,60.7,0.001208,50277.275087,0.800597,0.001509,Ban Conversion Practices
1,Belgium,47459,14805,320.56,eci_table_01,11484055.0,5.296067e+11,383,5.59,79.7,81.6,11259082.0,53.6,0.004133,46116.699234,3.205606,0.001289,Ban Conversion Practices
2,Bulgaria,2386,11985,19.91,eci_table_01,6975761.0,8.600000e+10,64,4.34,71.0,74.9,5256027.0,55.4,0.000342,12328.404026,0.199082,0.001718,Ban Conversion Practices
3,Croatia,8574,8460,101.35,eci_table_01,4067500.0,6.041555e+10,73,6.93,67.9,78.1,2328318.0,51.2,0.002108,14853.239837,1.013475,0.002080,Ban Conversion Practices
4,Cyprus,696,4230,16.45,eci_table_01,1198575.0,2.456465e+10,131,7.27,75.9,80.8,800708.0,63.1,0.000581,20494.877613,0.164539,0.003529,Ban Conversion Practices
5,Czech Republic,3774,14805,25.49,eci_table_01,10669709.0,2.464892e+11,139,1.93,64.1,79.0,7887156.0,60.6,0.000354,23101.777705,0.254914,0.001388,Ban Conversion Practices
6,Denmark,8587,9870,87.00,eci_table_01,5818553.0,3.480780e+11,137,4.91,80.6,81.0,5119978.0,62.2,0.001476,59822.092961,0.870010,0.001696,Ban Conversion Practices
7,Estonia,1519,4935,30.78,eci_table_01,1331824.0,3.138695e+10,31,5.11,69.6,78.2,916024.0,63.6,0.001141,23566.890205,0.307801,0.003705,Ban Conversion Practices
8,Finland,23618,9870,239.29,eci_table_01,5520314.0,2.687612e+11,18,6.59,88.2,81.7,4716888.0,59.1,0.004278,48685.853987,2.392908,0.001788,Ban Conversion Practices
9,France,580568,55695,1042.41,eci_table_01,67059887.0,2.715518e+12,119,8.43,65.6,82.5,54123364.0,55.1,0.008657,40493.928572,10.424060,0.000831,Ban Conversion Practices
10,Germany,92739,67680,137.03,eci_table_01,83132799.0,3.845630e+12,240,3.04,70.2,80.9,64324835.0,60.8,0.001116,46258.878290,1.370257,0.000814,Ban Conversion Practices
11,Greece,4127,14805,27.88,eci_table_01,10716322.0,2.098528e+11,81,17.24,136.6,81.3,8507474.0,51.8,0.000385,19582.536011,0.278757,0.001382,Ban Conversion Practices
12,Hungary,3195,14805,21.58,eci_table_01,9769949.0,1.609672e+11,107,3.40,48.5,75.8,6999582.0,56.5,0.000327,16475.741839,0.215805,0.001515,Ban Conversion Practices
13,Republic of Ireland,18503,9165,201.89,eci_table_01,5007069.0,3.886987e+11,72,4.93,77.8,82.3,3133123.0,62.1,0.003695,77629.988991,2.018876,0.001830,Ban Conversion Practices
14,Italy,60701,53580,113.29,eci_table_01,60297396.0,2.001244e+12,206,9.89,61.9,82.9,42651966.0,49.6,0.001007,33189.565799,1.132904,0.000889,Ban Conversion Practices
15,Latvia,1103,5640,19.56,eci_table_01,1912789.0,3.411720e+10,30,6.52,88.1,74.7,1304943.0,61.4,0.000577,17836.364887,0.195567,0.002949,Ban Conversion Practices
16,Lithuania,1973,7755,25.44,eci_table_01,2786844.0,5.421932e+10,43,6.35,72.4,75.7,1891013.0,61.6,0.000708,19455.454127,0.254417,0.002783,Ban Conversion Practices
17,Luxembourg,2091,4230,49.43,eci_table_01,645397.0,7.110492e+10,242,5.36,19.2,82.1,565488.0,59.3,0.003240,110172.373141,0.494326,0.006554,Ban Conversion Practices
18,Malta,861,4230,20.35,eci_table_01,502653.0,1.478616e+10,1380,3.47,54.3,82.3,475902.0,56.5,0.001713,29416.230606,0.203546,0.008415,Ban Conversion Practices
19,Netherlands,38112,20445,186.41,eci_table_01,17332850.0,9.090704e+11,508,3.20,85.0,81.8,15924729.0,63.6,0.002199,52447.831439,1.864123,0.001180,Ban Conversion Practices

#### Save the cleaned dataset to a new CSV file

In [161]:
merged_data.to_csv("C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Dissertation/MSc-Dissertation/data/Prepared Datasets/eci_merged_dataset.csv", index=False) # https://www.geeksforgeeks.org/pandas/saving-a-pandas-dataframe-as-a-csv/

print("Cleaned dataset has been saved as 'eci_merged_dataset.csv'.")

Cleaned dataset has been saved as 'eci_merged_dataset.csv'.

#### Quick check of the final dataset

In [162]:
print("Final dataset shape:", merged_data.shape)
print("First 5 rows of the final cleaned dataset:")
print(merged_data.head())

Final dataset shape: (729, 18)
First 5 rows of the final cleaned dataset:
    Country  Signatures  Threshold  Percentage   Petition_ID  Population  \
0   Austria       10724      13395       80.06  eci_table_01   8877067.0
1   Belgium       47459      14805      320.56  eci_table_01  11484055.0
2  Bulgaria        2386      11985       19.91  eci_table_01   6975761.0
3   Croatia        8574       8460      101.35  eci_table_01   4067500.0
4    Cyprus         696       4230       16.45  eci_table_01   1198575.0

            GDP  Population_Density  Unemployment_Rate  Tertiary_Enrollment  \
0  4.463147e+11                 109               4.67                 85.1
1  5.296067e+11                 383               5.59                 79.7
2  8.600000e+10                  64               4.34                 71.0
3  6.041555e+10                  73               6.93                 67.9
4  2.456465e+10                 131               7.27                 75.9

   Life_Expectancy  Urban_Population  Labor_Participation  \
0             81.6         5194416.0                 60.7
1             81.6        11259082.0                 53.6
2             74.9         5256027.0                 55.4
3             78.1         2328318.0                 51.2
4             80.8          800708.0                 63.1

   Signatures_Per_Capita  GDP_Per_Capita  Threshold_Ratio  \
0               0.001208    50277.275087         0.800597
1               0.004133    46116.699234         3.205606
2               0.000342    12328.404026         0.199082
3               0.002108    14853.239837         1.013475
4               0.000581    20494.877613         0.164539

   Threshold_Per_Capita             Petition_Name
0              0.001509  Ban Conversion Practices
1              0.001289  Ban Conversion Practices
2              0.001718  Ban Conversion Practices
3              0.002080  Ban Conversion Practices
4              0.003529  Ban Conversion Practices