### Matthew Riddell 
### D00245674
### MSc in Data Analytics
### Dissertation
### Extra Data Prepartation Jupyter Notebook


Extra data prepartion file for the creation of a new, petition level variable dataset

This dataset will be used for petition level factors analysis




### Link to each Dataset:

### ECI Petitions:
#### 2024

- ECI 01: https://citizens-initiative.europa.eu/initiatives/details/2024/000001_en Ban on conversion practices in the European Union
- ECI 02: https://citizens-initiative.europa.eu/initiatives/details/2024/000002_en European Citizens' Initiative in Defence of Agriculture and Rural Economy in Europe
- ECI 03: https://citizens-initiative.europa.eu/initiatives/details/2024/000004_en My Voice, My Choice: For Safe And Accessible Abortion
- ECI 04: https://citizens-initiative.europa.eu/initiatives/details/2024/000006_en Air-Quotas
- ECI 05: https://citizens-initiative.europa.eu/initiatives/details/2024/000007_en Stop Destroying Videogames
- ECI 06: https://citizens-initiative.europa.eu/initiatives/details/2024/000008_en Stop Cruelty Stop Slaughter
- ECI 07: https://citizens-initiative.europa.eu/initiatives/details/2024/000009_en STOP FAKE FOOD: ORIGIN ON LABEL
- ECI 08: https://citizens-initiative.europa.eu/initiatives/details/2024/000010_en ECI for a Water-Smart and Resilient Europe
- ECI 09: https://citizens-initiative.europa.eu/initiatives/details/2024/000011_en PsychedeliCare

#### 2023

- ECI 10: https://citizens-initiative.europa.eu/initiatives/details/2023/000001_en Stop torture and inhuman treatment at Europe’s borders
- ECI 11: https://citizens-initiative.europa.eu/initiatives/details/2023/000002_en Ensuring a dignified reception of migrants in Europe
- ECI 12: https://citizens-initiative.europa.eu/initiatives/details/2023/000003_en End The Horse Slaughter Age
- ECI 13: https://citizens-initiative.europa.eu/initiatives/details/2023/000004_en Connecting all European capitals and people through a high-speed train network
- ECI 14: https://citizens-initiative.europa.eu/initiatives/details/2023/000005_en Effective implementation of the concept of judicial precedent in EU countries
- ECI 15: https://citizens-initiative.europa.eu/initiatives/details/2023/000006_en Taxing great wealth to finance the ecological and social transition
- ECI 16: https://citizens-initiative.europa.eu/initiatives/details/2023/000007_en Preservation and development of Ukrainian culture, education, language, and traditions in EU states
- ECI 17: https://citizens-initiative.europa.eu/initiatives/details/2023/000008_en EU Live Bus Stop Info
- ECI 18: https://citizens-initiative.europa.eu/initiatives/details/2023/000009_en Trust and Freedom
- ECI 19: https://citizens-initiative.europa.eu/initiatives/details/2023/000011_en Creation of a European Environment Authority

#### 2022

- ECI 20: https://citizens-initiative.europa.eu/initiatives/details/2022/000001_en Win It On The Pitch 
- ECI 21: https://citizens-initiative.europa.eu/initiatives/details/2022/000002_en Fur Free Europe
- ECI 22: https://citizens-initiative.europa.eu/initiatives/details/2022/000003_en End The Slaughter Age
- ECI 23: https://citizens-initiative.europa.eu/initiatives/details/2022/000004_en Good Clothes, Fair Pay
- ECI 24: https://citizens-initiative.europa.eu/initiatives/details/2022/000007_en Protect the EU’s Rural Heritage, Food Security and Supply
- ECI 25: https://citizens-initiative.europa.eu/initiatives/details/2022/000008_en Focus on Specific Learning Disabilities on EU Level
- ECI 26: https://citizens-initiative.europa.eu/initiatives/details/2022/000009_en European Citizens’ Initiative for VEGAN MEAL
- ECI 27: https://citizens-initiative.europa.eu/initiatives/details/2022/000010_en European Day of "Whatever it Takes" 

### Worldstat Kaggle Dataset
https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

### Mahara Portfolio:
https://mahara.dkit.ie/view/view.php?t=f816cb6da6dd833aaa2f

### Github Repository:
https://github.com/Matthew-Riddell/MSc-Dissertation

In [16]:
import pandas as pd 
import numpy as np
import os

#### File path and file loading

In [17]:
file_path = r"C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Dissertation/MSc-Dissertation/data/Unprepared Datasets/"

# eci datasets
eci_files = [
    "eci_table_01.csv",
    "eci_table_02.csv",
    "eci_table_03.csv",
    "eci_table_04.csv",
    "eci_table_05.csv",
    "eci_table_06.csv",
    "eci_table_07.csv",
    "eci_table_08.csv",
    "eci_table_09.csv",
    "eci_table_10.csv",
    "eci_table_11.csv",
    "eci_table_12.csv",
    "eci_table_13.csv",
    "eci_table_14.csv",
    "eci_table_15.csv",
    "eci_table_16.csv",
    "eci_table_17.csv",
    "eci_table_18.csv",
    "eci_table_19.csv",
    "eci_table_20.csv",
    "eci_table_21.csv",
    "eci_table_22.csv",
    "eci_table_23.csv",
    "eci_table_24.csv",
    "eci_table_25.csv",
    "eci_table_26.csv",
    "eci_table_27.csv"
]

### Petition Names

In [18]:
petition_names = {
    "eci_table_01": "Ban Conversion Practices",
    "eci_table_02": "Defence of Agriculture",
    "eci_table_03": "My Voice My Choice",
    "eci_table_04": "Air-Quotas",
    "eci_table_05": "Stop Destroying Videogames",
    "eci_table_06": "Stop Cruelty Stop Slaughter",
    "eci_table_07": "STOP FAKE FOOD: ORIGIN ON LABEL",
    "eci_table_08": "Water-Smart and Resilient Europe",
    "eci_table_09": "PsychedeliCare",
    "eci_table_10": "Stop torture and inhuman treatment at Europe’s borders",
    "eci_table_11": "Ensuring a dignified reception of migrants in Europe",
    "eci_table_12": "End The Horse Slaughter Age",
    "eci_table_13": "Connecting European capitals via high-speed train network",
    "eci_table_14": "Implementation of the concept of judicial precedent",
    "eci_table_15": "Taxing wealth to finance ecological social transition",
    "eci_table_16": "Development of Ukrainian culture",
    "eci_table_17": "EU Live Bus Stop Info",
    "eci_table_18": "Trust and Freedom",
    "eci_table_19": "Creation of a European Environment Authority",
    "eci_table_20": "Win It On The Pitch",
    "eci_table_21": "Fur Free Europe",
    "eci_table_22": "End The Slaughter Age",
    "eci_table_23": "Good Clothes, Fair Pay",
    "eci_table_24": "Protect EU Rural Heritage, Food Security and Supply",
    "eci_table_25": "Focus on Specific Learning Disabilities",
    "eci_table_26": "VEGAN MEAL",
    "eci_table_27": "European Day of Whatever it Takes"
}

### Petition genres

In [19]:
petition_genres = {
    "eci_table_01": "Human Rights",
    "eci_table_02": "Agriculture",
    "eci_table_03": "Health",
    "eci_table_04": "Environment",
    "eci_table_05": "Digital Rights",
    "eci_table_06": "Animal Welfare",
    "eci_table_07": "Agriculture",
    "eci_table_08": "Environment",
    "eci_table_09": "Health",
    "eci_table_10": "Human Rights",
    "eci_table_11": "Migration",
    "eci_table_12": "Animal Welfare",
    "eci_table_13": "Transport",
    "eci_table_14": "Governance",
    "eci_table_15": "Economy",
    "eci_table_16": "Culture",
    "eci_table_17": "Technology",
    "eci_table_18": "Governance",
    "eci_table_19": "Environment",
    "eci_table_20": "Sport",
    "eci_table_21": "Animal Welfare",
    "eci_table_22": "Animal Welfare",
    "eci_table_23": "Employment",
    "eci_table_24": "Agriculture",
    "eci_table_25": "Education",
    "eci_table_26": "Food",
    "eci_table_27": "Politics"
}

### Function to manually add the year the ECI was created based on the dataset number

In [20]:
def get_year(number):

    if number <= 9:
        return 2024
    elif number <= 19:
        return 2023
    else:
        return 2022

### Loop through each individual dataset, extract data and add variables to new list

loop through each file 

dataset id determined by file name,

using file name apply the petition year (datasets were scraped in order so they are batched in numerical order)

read the dataframe to extract the total signatures row, using iloc to grab first column of all rows and finding the one that contains "Total"

if the row isn't empty, it grabs the second column and sets it as a new total_signatures variable

otherwise it makes it a NaN if no row was located

for each petition, a dictionary is created with the new variables and each dictionary is appended to a list

In [21]:
petition_data = []

for file in eci_files:

    dataset_id = file.replace(".csv", "")
    petition_number = int(dataset_id.split("_")[-1])

    df = pd.read_csv(os.path.join(file_path, file))

    # Find the total signatures row
    total_row = df[df.iloc[:, 0].astype(str).str.contains("Total", case=False, na=False)]

    if not total_row.empty:
        value = total_row.iloc[0, 1]
        total_signatures = int(str(value).replace(",", "").strip())
    else:
        total_signatures = None

    # Store petition metadata
    petition_data.append({
        "Petition_ID": dataset_id,
        "Petition_Number": petition_number,
        "Year": get_year(petition_number),
        "Petition_Name": petition_names[dataset_id],
        "Genre": petition_genres[dataset_id],
        "Total_Signatures": total_signatures,
        "Successful": total_signatures >= 1_000_000 if total_signatures is not None else False
    })

### Create a new dataframe based on the petition data list

In [22]:
petition_df = pd.DataFrame(petition_data)

### Sort dataframe by petition number

In [23]:
# Sort by petition number
petition_df = petition_df.sort_values("Petition_Number").reset_index(drop=True)

### Preview data

In [24]:
print(petition_df)

     Petition_ID  Petition_Number  Year  \
0   eci_table_01                1  2024
1   eci_table_02                2  2024
2   eci_table_03                3  2024
3   eci_table_04                4  2024
4   eci_table_05                5  2024
5   eci_table_06                6  2024
6   eci_table_07                7  2024
7   eci_table_08                8  2024
8   eci_table_09                9  2024
9   eci_table_10               10  2023
10  eci_table_11               11  2023
11  eci_table_12               12  2023
12  eci_table_13               13  2023
13  eci_table_14               14  2023
14  eci_table_15               15  2023
15  eci_table_16               16  2023
16  eci_table_17               17  2023
17  eci_table_18               18  2023
18  eci_table_19               19  2023
19  eci_table_20               20  2022
20  eci_table_21               21  2022
21  eci_table_22               22  2022
22  eci_table_23               23  2022
23  eci_table_24               24  2022
24  eci_table_25               25  2022
25  eci_table_26               26  2022
26  eci_table_27               27  2022

                                        Petition_Name           Genre  \
0                            Ban Conversion Practices    Human Rights
1                              Defence of Agriculture     Agriculture
2                                  My Voice My Choice          Health
3                                          Air-Quotas     Environment
4                          Stop Destroying Videogames  Digital Rights
5                         Stop Cruelty Stop Slaughter  Animal Welfare
6                     STOP FAKE FOOD: ORIGIN ON LABEL     Agriculture
7                    Water-Smart and Resilient Europe     Environment
8                                      PsychedeliCare          Health
9   Stop torture and inhuman treatment at Europe’s...    Human Rights
10  Ensuring a dignified reception of migrants in ...       Migration
11                        End The Horse Slaughter Age  Animal Welfare
12  Connecting European capitals via high-speed tr...       Transport
13  Implementation of the concept of judicial prec...      Governance
14  Taxing wealth to finance ecological social tra...         Economy
15                   Development of Ukrainian culture         Culture
16                              EU Live Bus Stop Info      Technology
17                                  Trust and Freedom      Governance
18       Creation of a European Environment Authority     Environment
19                                Win It On The Pitch           Sport
20                                    Fur Free Europe  Animal Welfare
21                              End The Slaughter Age  Animal Welfare
22                             Good Clothes, Fair Pay      Employment
23  Protect EU Rural Heritage, Food Security and S...     Agriculture
24            Focus on Specific Learning Disabilities       Education
25                                         VEGAN MEAL            Food
26                  European Day of Whatever it Takes        Politics

    Total_Signatures  Successful
0            1128063        True
1               4432       False
2            1124513        True
3               7278       False
4            1294188        True
5             590368       False
6             868587       False
7               4442       False
8              74016       False
9              25124       False
10             15364       False
11             15154       False
12             40682       False
13               291       False
14            357155       False
15              1095       False
16              3746       False
17             22471       False
18             14764       False
19              3594       False
20           1502319        True
21            867946       False
22            216100       False
23             21410       False
24              1327       False
25              8003       False
26               254       False

### Dataset shape

In [26]:
print(petition_df.shape)

(27, 7)

#### Display first 5 rows of the new dataset

In [25]:
petition_df.head()

,Petition_ID,Petition_Number,Year,Petition_Name,Genre,Total_Signatures,Successful
0,eci_table_01,1,2024,Ban Conversion Practices,Human Rights,1128063,True
1,eci_table_02,2,2024,Defence of Agriculture,Agriculture,4432,False
2,eci_table_03,3,2024,My Voice My Choice,Health,1124513,True
3,eci_table_04,4,2024,Air-Quotas,Environment,7278,False
4,eci_table_05,5,2024,Stop Destroying Videogames,Digital Rights,1294188,True

In [27]:
print("First 5 rows of the data:")
print(petition_df.head())

First 5 rows of the data:
    Petition_ID  Petition_Number  Year               Petition_Name  \
0  eci_table_01                1  2024    Ban Conversion Practices
1  eci_table_02                2  2024      Defence of Agriculture
2  eci_table_03                3  2024          My Voice My Choice
3  eci_table_04                4  2024                  Air-Quotas
4  eci_table_05                5  2024  Stop Destroying Videogames

            Genre  Total_Signatures  Successful
0    Human Rights           1128063        True
1     Agriculture              4432       False
2          Health           1124513        True
3     Environment              7278       False
4  Digital Rights           1294188        True

#### Check basic information about the dataset

In [28]:
print("Information about the dataset:")
print(petition_df.info())

Information about the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Petition_ID       27 non-null     object
 1   Petition_Number   27 non-null     int64
 2   Year              27 non-null     int64
 3   Petition_Name     27 non-null     object
 4   Genre             27 non-null     object
 5   Total_Signatures  27 non-null     int64
 6   Successful        27 non-null     bool
dtypes: bool(1), int64(3), object(3)
memory usage: 1.4+ KB
None

### Missing values per column

In [29]:
petition_df.isnull().sum()

Petition_ID         0
Petition_Number     0
Year                0
Petition_Name       0
Genre               0
Total_Signatures    0
Successful          0
dtype: int64

### Total missing values

In [30]:
total_missing = petition_df.isna().sum().sum()
print("Total missing values in the dataset:", total_missing)

Total missing values in the dataset: 0

### Display column names

In [31]:
print("Column names:")
print(petition_df.columns)

Column names:
Index(['Petition_ID', 'Petition_Number', 'Year', 'Petition_Name', 'Genre',
       'Total_Signatures', 'Successful'],
      dtype='object')

### Duplication Checking

In [33]:
print(petition_df.duplicated().sum())

0

### Final checking of dataset before exporting

In [34]:
petition_df.head(27)

,Petition_ID,Petition_Number,Year,Petition_Name,Genre,Total_Signatures,Successful
0,eci_table_01,1,2024,Ban Conversion Practices,Human Rights,1128063,True
1,eci_table_02,2,2024,Defence of Agriculture,Agriculture,4432,False
2,eci_table_03,3,2024,My Voice My Choice,Health,1124513,True
3,eci_table_04,4,2024,Air-Quotas,Environment,7278,False
4,eci_table_05,5,2024,Stop Destroying Videogames,Digital Rights,1294188,True
5,eci_table_06,6,2024,Stop Cruelty Stop Slaughter,Animal Welfare,590368,False
6,eci_table_07,7,2024,STOP FAKE FOOD: ORIGIN ON LABEL,Agriculture,868587,False
7,eci_table_08,8,2024,Water-Smart and Resilient Europe,Environment,4442,False
8,eci_table_09,9,2024,PsychedeliCare,Health,74016,False
9,eci_table_10,10,2023,Stop torture and inhuman treatment at Europe’s...,Human Rights,25124,False
10,eci_table_11,11,2023,Ensuring a dignified reception of migrants in ...,Migration,15364,False
11,eci_table_12,12,2023,End The Horse Slaughter Age,Animal Welfare,15154,False
12,eci_table_13,13,2023,Connecting European capitals via high-speed tr...,Transport,40682,False
13,eci_table_14,14,2023,Implementation of the concept of judicial prec...,Governance,291,False
14,eci_table_15,15,2023,Taxing wealth to finance ecological social tra...,Economy,357155,False
15,eci_table_16,16,2023,Development of Ukrainian culture,Culture,1095,False
16,eci_table_17,17,2023,EU Live Bus Stop Info,Technology,3746,False
17,eci_table_18,18,2023,Trust and Freedom,Governance,22471,False
18,eci_table_19,19,2023,Creation of a European Environment Authority,Environment,14764,False
19,eci_table_20,20,2022,Win It On The Pitch,Sport,3594,False
20,eci_table_21,21,2022,Fur Free Europe,Animal Welfare,1502319,True
21,eci_table_22,22,2022,End The Slaughter Age,Animal Welfare,867946,False
22,eci_table_23,23,2022,"Good Clothes, Fair Pay",Employment,216100,False
23,eci_table_24,24,2022,"Protect EU Rural Heritage, Food Security and S...",Agriculture,21410,False
24,eci_table_25,25,2022,Focus on Specific Learning Disabilities,Education,1327,False
25,eci_table_26,26,2022,VEGAN MEAL,Food,8003,False
26,eci_table_27,27,2022,European Day of Whatever it Takes,Politics,254,False

In [35]:
petition_df.to_csv("C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Dissertation/MSc-Dissertation/data/Prepared Datasets/eci_petition_metadata.csv", index=False) # https://www.geeksforgeeks.org/pandas/saving-a-pandas-dataframe-as-a-csv/

print("Cleaned dataset has been saved as 'eci_petition_metadata.csv'.")

Cleaned dataset has been saved as 'eci_petition_metadata.csv'.