### Matthew Riddell 
### D00245674
### MSc in Data Analytics
### Dissertation
### Extra Data Prepartation Jupyter Notebook

Post Interim Report Data Preparation for the incorporation of new datasets and variables

Extra data prepartion file for the creation of a new, petition level variable dataset

This dataset will be used for petition level factors analysis

Extra Data Prepartion for the creation of a Master Dataset combinining all new datasets to the existing combined dataset from pre-interim report




### Link to each Dataset:

### ECI Petitions:
#### 2024

- ECI 01: https://citizens-initiative.europa.eu/initiatives/details/2024/000001_en Ban on conversion practices in the European Union
- ECI 02: https://citizens-initiative.europa.eu/initiatives/details/2024/000002_en European Citizens' Initiative in Defence of Agriculture and Rural Economy in Europe
- ECI 03: https://citizens-initiative.europa.eu/initiatives/details/2024/000004_en My Voice, My Choice: For Safe And Accessible Abortion
- ECI 04: https://citizens-initiative.europa.eu/initiatives/details/2024/000006_en Air-Quotas
- ECI 05: https://citizens-initiative.europa.eu/initiatives/details/2024/000007_en Stop Destroying Videogames
- ECI 06: https://citizens-initiative.europa.eu/initiatives/details/2024/000008_en Stop Cruelty Stop Slaughter
- ECI 07: https://citizens-initiative.europa.eu/initiatives/details/2024/000009_en STOP FAKE FOOD: ORIGIN ON LABEL
- ECI 08: https://citizens-initiative.europa.eu/initiatives/details/2024/000010_en ECI for a Water-Smart and Resilient Europe
- ECI 09: https://citizens-initiative.europa.eu/initiatives/details/2024/000011_en PsychedeliCare

#### 2023

- ECI 10: https://citizens-initiative.europa.eu/initiatives/details/2023/000001_en Stop torture and inhuman treatment at Europe’s borders
- ECI 11: https://citizens-initiative.europa.eu/initiatives/details/2023/000002_en Ensuring a dignified reception of migrants in Europe
- ECI 12: https://citizens-initiative.europa.eu/initiatives/details/2023/000003_en End The Horse Slaughter Age
- ECI 13: https://citizens-initiative.europa.eu/initiatives/details/2023/000004_en Connecting all European capitals and people through a high-speed train network
- ECI 14: https://citizens-initiative.europa.eu/initiatives/details/2023/000005_en Effective implementation of the concept of judicial precedent in EU countries
- ECI 15: https://citizens-initiative.europa.eu/initiatives/details/2023/000006_en Taxing great wealth to finance the ecological and social transition
- ECI 16: https://citizens-initiative.europa.eu/initiatives/details/2023/000007_en Preservation and development of Ukrainian culture, education, language, and traditions in EU states
- ECI 17: https://citizens-initiative.europa.eu/initiatives/details/2023/000008_en EU Live Bus Stop Info
- ECI 18: https://citizens-initiative.europa.eu/initiatives/details/2023/000009_en Trust and Freedom
- ECI 19: https://citizens-initiative.europa.eu/initiatives/details/2023/000011_en Creation of a European Environment Authority

#### 2022

- ECI 20: https://citizens-initiative.europa.eu/initiatives/details/2022/000001_en Win It On The Pitch 
- ECI 21: https://citizens-initiative.europa.eu/initiatives/details/2022/000002_en Fur Free Europe
- ECI 22: https://citizens-initiative.europa.eu/initiatives/details/2022/000003_en End The Slaughter Age
- ECI 23: https://citizens-initiative.europa.eu/initiatives/details/2022/000004_en Good Clothes, Fair Pay
- ECI 24: https://citizens-initiative.europa.eu/initiatives/details/2022/000007_en Protect the EU’s Rural Heritage, Food Security and Supply
- ECI 25: https://citizens-initiative.europa.eu/initiatives/details/2022/000008_en Focus on Specific Learning Disabilities on EU Level
- ECI 26: https://citizens-initiative.europa.eu/initiatives/details/2022/000009_en European Citizens’ Initiative for VEGAN MEAL
- ECI 27: https://citizens-initiative.europa.eu/initiatives/details/2022/000010_en European Day of "Whatever it Takes" 

### Worldstat Kaggle Dataset
https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

### 2023 Global Development and Prosperity Index 
https://www.kaggle.com/datasets/tarktunataalt/2023-global-country-development-and-prosperity-index

### Media Literacy Index Dataset 2023
https://osis.bg/wp-content/uploads/2023/06/MLI-report-in-English-22.06.pdf

https://osis.bg/?p=4450&lang=en

### Mahara Portfolio:
https://mahara.dkit.ie/view/view.php?t=f816cb6da6dd833aaa2f

### Github Repository:
https://github.com/Matthew-Riddell/MSc-Dissertation

In [57]:
import pandas as pd 
import numpy as np
import os

#### File path and file loading

In [58]:
file_path = r"C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Dissertation/MSc-Dissertation/data/Unprepared Datasets/"

# eci datasets
eci_files = [
    "eci_table_01.csv",
    "eci_table_02.csv",
    "eci_table_03.csv",
    "eci_table_04.csv",
    "eci_table_05.csv",
    "eci_table_06.csv",
    "eci_table_07.csv",
    "eci_table_08.csv",
    "eci_table_09.csv",
    "eci_table_10.csv",
    "eci_table_11.csv",
    "eci_table_12.csv",
    "eci_table_13.csv",
    "eci_table_14.csv",
    "eci_table_15.csv",
    "eci_table_16.csv",
    "eci_table_17.csv",
    "eci_table_18.csv",
    "eci_table_19.csv",
    "eci_table_20.csv",
    "eci_table_21.csv",
    "eci_table_22.csv",
    "eci_table_23.csv",
    "eci_table_24.csv",
    "eci_table_25.csv",
    "eci_table_26.csv",
    "eci_table_27.csv"
]

### Petition Names

In [59]:
petition_names = {
    "eci_table_01": "Ban Conversion Practices",
    "eci_table_02": "Defence of Agriculture",
    "eci_table_03": "My Voice My Choice",
    "eci_table_04": "Air-Quotas",
    "eci_table_05": "Stop Destroying Videogames",
    "eci_table_06": "Stop Cruelty Stop Slaughter",
    "eci_table_07": "STOP FAKE FOOD: ORIGIN ON LABEL",
    "eci_table_08": "Water-Smart and Resilient Europe",
    "eci_table_09": "PsychedeliCare",
    "eci_table_10": "Stop torture and inhuman treatment at Europe’s borders",
    "eci_table_11": "Ensuring a dignified reception of migrants in Europe",
    "eci_table_12": "End The Horse Slaughter Age",
    "eci_table_13": "Connecting European capitals via high-speed train network",
    "eci_table_14": "Implementation of the concept of judicial precedent",
    "eci_table_15": "Taxing wealth to finance ecological social transition",
    "eci_table_16": "Development of Ukrainian culture",
    "eci_table_17": "EU Live Bus Stop Info",
    "eci_table_18": "Trust and Freedom",
    "eci_table_19": "Creation of a European Environment Authority",
    "eci_table_20": "Win It On The Pitch",
    "eci_table_21": "Fur Free Europe",
    "eci_table_22": "End The Slaughter Age",
    "eci_table_23": "Good Clothes, Fair Pay",
    "eci_table_24": "Protect EU Rural Heritage, Food Security and Supply",
    "eci_table_25": "Focus on Specific Learning Disabilities",
    "eci_table_26": "VEGAN MEAL",
    "eci_table_27": "European Day of Whatever it Takes"
}

### Petition genres

In [60]:
petition_genres = {
    "eci_table_01": "Human Rights",
    "eci_table_02": "Agriculture",
    "eci_table_03": "Health",
    "eci_table_04": "Environment",
    "eci_table_05": "Digital Rights",
    "eci_table_06": "Animal Welfare",
    "eci_table_07": "Agriculture",
    "eci_table_08": "Environment",
    "eci_table_09": "Health",
    "eci_table_10": "Human Rights",
    "eci_table_11": "Migration",
    "eci_table_12": "Animal Welfare",
    "eci_table_13": "Transport",
    "eci_table_14": "Governance",
    "eci_table_15": "Economy",
    "eci_table_16": "Culture",
    "eci_table_17": "Technology",
    "eci_table_18": "Governance",
    "eci_table_19": "Environment",
    "eci_table_20": "Sport",
    "eci_table_21": "Animal Welfare",
    "eci_table_22": "Animal Welfare",
    "eci_table_23": "Employment",
    "eci_table_24": "Agriculture",
    "eci_table_25": "Education",
    "eci_table_26": "Food",
    "eci_table_27": "Politics"
}

### Function to manually add the year the ECI was created based on the dataset number

In [61]:
def get_year(number):

    if number <= 9:
        return 2024
    elif number <= 19:
        return 2023
    else:
        return 2022

### Loop through each individual dataset, extract data and add variables to new list

loop through each file 

dataset id determined by file name,

using file name apply the petition year (datasets were scraped in order so they are batched in numerical order)

read the dataframe to extract the total signatures row, using iloc to grab first column of all rows and finding the one that contains "Total"

if the row isn't empty, it grabs the second column and sets it as a new total_signatures variable

otherwise it makes it a NaN if no row was located

for each petition, a dictionary is created with the new variables and each dictionary is appended to a list

In [62]:
petition_data = []

for file in eci_files:

    dataset_id = file.replace(".csv", "")
    petition_number = int(dataset_id.split("_")[-1])

    df = pd.read_csv(os.path.join(file_path, file))

    # Find the total signatures row
    total_row = df[df.iloc[:, 0].astype(str).str.contains("Total", case=False, na=False)]

    if not total_row.empty:
        value = total_row.iloc[0, 1]
        total_signatures = int(str(value).replace(",", "").strip())
    else:
        total_signatures = None

    # Store petition metadata
    petition_data.append({
        "Petition_ID": dataset_id,
        "Petition_Number": petition_number,
        "Year": get_year(petition_number),
        "Petition_Name": petition_names[dataset_id],
        "Genre": petition_genres[dataset_id],
        "Total_Signatures": total_signatures,
        "Successful": total_signatures >= 1_000_000 if total_signatures is not None else False
    })

### Create a new dataframe based on the petition data list

In [63]:
petition_df = pd.DataFrame(petition_data)

### Sort dataframe by petition number

In [64]:
# Sort by petition number
petition_df = petition_df.sort_values("Petition_Number").reset_index(drop=True)

### Preview data

In [65]:
print(petition_df)

     Petition_ID  Petition_Number  Year  \
0   eci_table_01                1  2024
1   eci_table_02                2  2024
2   eci_table_03                3  2024
3   eci_table_04                4  2024
4   eci_table_05                5  2024
5   eci_table_06                6  2024
6   eci_table_07                7  2024
7   eci_table_08                8  2024
8   eci_table_09                9  2024
9   eci_table_10               10  2023
10  eci_table_11               11  2023
11  eci_table_12               12  2023
12  eci_table_13               13  2023
13  eci_table_14               14  2023
14  eci_table_15               15  2023
15  eci_table_16               16  2023
16  eci_table_17               17  2023
17  eci_table_18               18  2023
18  eci_table_19               19  2023
19  eci_table_20               20  2022
20  eci_table_21               21  2022
21  eci_table_22               22  2022
22  eci_table_23               23  2022
23  eci_table_24               24  2022
24  eci_table_25               25  2022
25  eci_table_26               26  2022
26  eci_table_27               27  2022

                                        Petition_Name           Genre  \
0                            Ban Conversion Practices    Human Rights
1                              Defence of Agriculture     Agriculture
2                                  My Voice My Choice          Health
3                                          Air-Quotas     Environment
4                          Stop Destroying Videogames  Digital Rights
5                         Stop Cruelty Stop Slaughter  Animal Welfare
6                     STOP FAKE FOOD: ORIGIN ON LABEL     Agriculture
7                    Water-Smart and Resilient Europe     Environment
8                                      PsychedeliCare          Health
9   Stop torture and inhuman treatment at Europe’s...    Human Rights
10  Ensuring a dignified reception of migrants in ...       Migration
11                        End The Horse Slaughter Age  Animal Welfare
12  Connecting European capitals via high-speed tr...       Transport
13  Implementation of the concept of judicial prec...      Governance
14  Taxing wealth to finance ecological social tra...         Economy
15                   Development of Ukrainian culture         Culture
16                              EU Live Bus Stop Info      Technology
17                                  Trust and Freedom      Governance
18       Creation of a European Environment Authority     Environment
19                                Win It On The Pitch           Sport
20                                    Fur Free Europe  Animal Welfare
21                              End The Slaughter Age  Animal Welfare
22                             Good Clothes, Fair Pay      Employment
23  Protect EU Rural Heritage, Food Security and S...     Agriculture
24            Focus on Specific Learning Disabilities       Education
25                                         VEGAN MEAL            Food
26                  European Day of Whatever it Takes        Politics

    Total_Signatures  Successful
0            1128063        True
1               4432       False
2            1124513        True
3               7278       False
4            1294188        True
5             590368       False
6             868587       False
7               4442       False
8              74016       False
9              25124       False
10             15364       False
11             15154       False
12             40682       False
13               291       False
14            357155       False
15              1095       False
16              3746       False
17             22471       False
18             14764       False
19              3594       False
20           1502319        True
21            867946       False
22            216100       False
23             21410       False
24              1327       False
25              8003       False
26               254       False

### Dataset shape

In [66]:
print(petition_df.shape)

(27, 7)

#### Display first 5 rows of the new dataset

In [67]:
petition_df.head()

,Petition_ID,Petition_Number,Year,Petition_Name,Genre,Total_Signatures,Successful
0,eci_table_01,1,2024,Ban Conversion Practices,Human Rights,1128063,True
1,eci_table_02,2,2024,Defence of Agriculture,Agriculture,4432,False
2,eci_table_03,3,2024,My Voice My Choice,Health,1124513,True
3,eci_table_04,4,2024,Air-Quotas,Environment,7278,False
4,eci_table_05,5,2024,Stop Destroying Videogames,Digital Rights,1294188,True

In [68]:
print("First 5 rows of the data:")
print(petition_df.head())

First 5 rows of the data:
    Petition_ID  Petition_Number  Year               Petition_Name  \
0  eci_table_01                1  2024    Ban Conversion Practices
1  eci_table_02                2  2024      Defence of Agriculture
2  eci_table_03                3  2024          My Voice My Choice
3  eci_table_04                4  2024                  Air-Quotas
4  eci_table_05                5  2024  Stop Destroying Videogames

            Genre  Total_Signatures  Successful
0    Human Rights           1128063        True
1     Agriculture              4432       False
2          Health           1124513        True
3     Environment              7278       False
4  Digital Rights           1294188        True

#### Check basic information about the dataset

In [69]:
print("Information about the dataset:")
print(petition_df.info())

Information about the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Petition_ID       27 non-null     object
 1   Petition_Number   27 non-null     int64
 2   Year              27 non-null     int64
 3   Petition_Name     27 non-null     object
 4   Genre             27 non-null     object
 5   Total_Signatures  27 non-null     int64
 6   Successful        27 non-null     bool
dtypes: bool(1), int64(3), object(3)
memory usage: 1.4+ KB
None

### Missing values per column

In [70]:
petition_df.isnull().sum()

Petition_ID         0
Petition_Number     0
Year                0
Petition_Name       0
Genre               0
Total_Signatures    0
Successful          0
dtype: int64

### Total missing values

In [71]:
total_missing = petition_df.isna().sum().sum()
print("Total missing values in the dataset:", total_missing)

Total missing values in the dataset: 0

### Display column names

In [72]:
print("Column names:")
print(petition_df.columns)

Column names:
Index(['Petition_ID', 'Petition_Number', 'Year', 'Petition_Name', 'Genre',
       'Total_Signatures', 'Successful'],
      dtype='object')

### Duplication Checking

In [73]:
print(petition_df.duplicated().sum())

0

### Final checking of dataset before exporting

In [74]:
petition_df.head(27)

,Petition_ID,Petition_Number,Year,Petition_Name,Genre,Total_Signatures,Successful
0,eci_table_01,1,2024,Ban Conversion Practices,Human Rights,1128063,True
1,eci_table_02,2,2024,Defence of Agriculture,Agriculture,4432,False
2,eci_table_03,3,2024,My Voice My Choice,Health,1124513,True
3,eci_table_04,4,2024,Air-Quotas,Environment,7278,False
4,eci_table_05,5,2024,Stop Destroying Videogames,Digital Rights,1294188,True
5,eci_table_06,6,2024,Stop Cruelty Stop Slaughter,Animal Welfare,590368,False
6,eci_table_07,7,2024,STOP FAKE FOOD: ORIGIN ON LABEL,Agriculture,868587,False
7,eci_table_08,8,2024,Water-Smart and Resilient Europe,Environment,4442,False
8,eci_table_09,9,2024,PsychedeliCare,Health,74016,False
9,eci_table_10,10,2023,Stop torture and inhuman treatment at Europe’s...,Human Rights,25124,False
10,eci_table_11,11,2023,Ensuring a dignified reception of migrants in ...,Migration,15364,False
11,eci_table_12,12,2023,End The Horse Slaughter Age,Animal Welfare,15154,False
12,eci_table_13,13,2023,Connecting European capitals via high-speed tr...,Transport,40682,False
13,eci_table_14,14,2023,Implementation of the concept of judicial prec...,Governance,291,False
14,eci_table_15,15,2023,Taxing wealth to finance ecological social tra...,Economy,357155,False
15,eci_table_16,16,2023,Development of Ukrainian culture,Culture,1095,False
16,eci_table_17,17,2023,EU Live Bus Stop Info,Technology,3746,False
17,eci_table_18,18,2023,Trust and Freedom,Governance,22471,False
18,eci_table_19,19,2023,Creation of a European Environment Authority,Environment,14764,False
19,eci_table_20,20,2022,Win It On The Pitch,Sport,3594,False
20,eci_table_21,21,2022,Fur Free Europe,Animal Welfare,1502319,True
21,eci_table_22,22,2022,End The Slaughter Age,Animal Welfare,867946,False
22,eci_table_23,23,2022,"Good Clothes, Fair Pay",Employment,216100,False
23,eci_table_24,24,2022,"Protect EU Rural Heritage, Food Security and S...",Agriculture,21410,False
24,eci_table_25,25,2022,Focus on Specific Learning Disabilities,Education,1327,False
25,eci_table_26,26,2022,VEGAN MEAL,Food,8003,False
26,eci_table_27,27,2022,European Day of Whatever it Takes,Politics,254,False

In [75]:
petition_df.to_csv("C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Dissertation/MSc-Dissertation/data/Prepared Datasets/eci_petition_metadata.csv", index=False) # https://www.geeksforgeeks.org/pandas/saving-a-pandas-dataframe-as-a-csv/

print("Cleaned dataset has been saved as 'eci_petition_metadata.csv'.")

Cleaned dataset has been saved as 'eci_petition_metadata.csv'.

## Creation of Combined Master Dataset

At this stage I combine the existing completed petition metadata dataset with the combined eci dataset and add the other new datasets for country level prosperity index and media literacy

### File paths and names

In [76]:
file_path = r"C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Dissertation/MSc-Dissertation/data/Unprepared Datasets/"

file_eci_merged_dataset = "eci_merged_dataset.csv"

file_eci_petition_metadata = "eci_petition_metadata.csv"

file_development_and_prosperity_index_2023 = "development_and_prosperity_index_2023.csv"

file_media_literacy_index_2023 = "media_literacy_index_2023.csv"

Combine file paths

In [77]:
file_eci = os.path.join(file_path, file_eci_merged_dataset)
file_petitions = os.path.join(file_path, file_eci_petition_metadata)
file_prosperity = os.path.join(file_path, file_development_and_prosperity_index_2023)
file_media = os.path.join(file_path, file_media_literacy_index_2023)

Read csv files

In [78]:
eci = pd.read_csv(file_eci)
petition_metadata = pd.read_csv(file_petitions)
prosperity = pd.read_csv(file_prosperity)
media = pd.read_csv(file_media)

### Preview Datasets

Dataset Info

In [79]:
print(eci.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 729 entries, 0 to 728
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                729 non-null    object
 1   Signatures             729 non-null    int64
 2   Threshold              729 non-null    int64
 3   Percentage             729 non-null    float64
 4   Petition_ID            729 non-null    object
 5   Population             729 non-null    float64
 6   GDP                    729 non-null    float64
 7   Population_Density     729 non-null    int64
 8   Unemployment_Rate      729 non-null    float64
 9   Tertiary_Enrollment    729 non-null    float64
 10  Life_Expectancy        729 non-null    float64
 11  Urban_Population       729 non-null    float64
 12  Labor_Participation    729 non-null    float64
 13  Signatures_Per_Capita  729 non-null    float64
 14  GDP_Per_Capita         729 non-null    float64
 15  Threshold_Ratio        729 non-null    float64
 16  Threshold_Per_Capita   729 non-null    float64
 17  Petition_Name          729 non-null    object
dtypes: float64(12), int64(3), object(3)
memory usage: 102.6+ KB
None

In [80]:
print(petition_metadata.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Petition_ID       27 non-null     object
 1   Petition_Number   27 non-null     int64
 2   Year              27 non-null     int64
 3   Petition_Name     27 non-null     object
 4   Genre             27 non-null     object
 5   Total_Signatures  27 non-null     int64
 6   Successful        27 non-null     bool
dtypes: bool(1), int64(3), object(3)
memory usage: 1.4+ KB
None

In [81]:
print(prosperity.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Country                     167 non-null    object
 1   AveragScore                 167 non-null    float64
 2   SafetySecurity              167 non-null    float64
 3   PersonelFreedom             167 non-null    float64
 4   Governance                  167 non-null    float64
 5   SocialCapital               167 non-null    float64
 6   InvestmentEnvironment       167 non-null    float64
 7   EnterpriseConditions        167 non-null    float64
 8   MarketAccessInfrastructure  167 non-null    float64
 9   EconomicQuality             167 non-null    float64
 10  LivingConditions            167 non-null    float64
 11  Health                      167 non-null    float64
 12  Education                   167 non-null    float64
 13  NaturalEnvironment          167 non-null    float64
dtypes: float64(13), object(1)
memory usage: 18.4+ KB
None

In [82]:
print(media.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     41 non-null     int64
 1   Country  41 non-null     object
 2   Score    41 non-null     int64
 3   Cluster  41 non-null     int64
dtypes: int64(3), object(1)
memory usage: 1.4+ KB
None

### Display first 5 rows of each dataset

In [83]:
eci.head()

,Country,Signatures,Threshold,Percentage,Petition_ID,Population,GDP,Population_Density,Unemployment_Rate,Tertiary_Enrollment,Life_Expectancy,Urban_Population,Labor_Participation,Signatures_Per_Capita,GDP_Per_Capita,Threshold_Ratio,Threshold_Per_Capita,Petition_Name
0,Austria,10724,13395,80.06,eci_table_01,8877067.0,4.463147e+11,109,4.67,85.1,81.6,5194416.0,60.7,0.001208,50277.275087,0.800597,0.001509,Ban Conversion Practices
1,Belgium,47459,14805,320.56,eci_table_01,11484055.0,5.296067e+11,383,5.59,79.7,81.6,11259082.0,53.6,0.004133,46116.699234,3.205606,0.001289,Ban Conversion Practices
2,Bulgaria,2386,11985,19.91,eci_table_01,6975761.0,8.600000e+10,64,4.34,71.0,74.9,5256027.0,55.4,0.000342,12328.404026,0.199082,0.001718,Ban Conversion Practices
3,Croatia,8574,8460,101.35,eci_table_01,4067500.0,6.041555e+10,73,6.93,67.9,78.1,2328318.0,51.2,0.002108,14853.239837,1.013475,0.002080,Ban Conversion Practices
4,Cyprus,696,4230,16.45,eci_table_01,1198575.0,2.456465e+10,131,7.27,75.9,80.8,800708.0,63.1,0.000581,20494.877613,0.164539,0.003529,Ban Conversion Practices

In [84]:
petition_metadata.head()

,Petition_ID,Petition_Number,Year,Petition_Name,Genre,Total_Signatures,Successful
0,eci_table_01,1,2024,Ban Conversion Practices,Human Rights,1128063,True
1,eci_table_02,2,2024,Defence of Agriculture,Agriculture,4432,False
2,eci_table_03,3,2024,My Voice My Choice,Health,1124513,True
3,eci_table_04,4,2024,Air-Quotas,Environment,7278,False
4,eci_table_05,5,2024,Stop Destroying Videogames,Digital Rights,1294188,True

In [85]:
prosperity.head()

,Country,AveragScore,SafetySecurity,PersonelFreedom,Governance,SocialCapital,InvestmentEnvironment,EnterpriseConditions,MarketAccessInfrastructure,EconomicQuality,LivingConditions,Health,Education,NaturalEnvironment
0,Denmark,84.55,92.59,94.09,89.45,82.56,82.42,79.64,78.79,76.81,95.77,81.07,87.48,73.94
1,Sweden,83.67,90.97,91.90,86.41,78.29,82.81,75.54,79.67,76.18,95.33,82.28,85.92,78.74
2,Norway,83.59,93.30,94.10,89.66,79.03,82.24,75.95,75.87,77.25,94.70,82.98,85.68,72.37
3,Finland,83.47,89.56,91.96,90.41,77.27,84.12,77.25,78.77,70.28,94.46,81.19,88.38,77.99
4,Switzerland,83.42,95.66,87.50,87.67,69.14,80.81,83.84,78.65,79.71,94.66,82.11,87.72,73.60

In [86]:

media.head()

   Rank  Country  Score  Cluster
0     1  Finland     74        1
1     2  Denmark     73        1
2     3   Norway     72        1
3     4  Estonia     71        1
4     5   Sweden     71        1

### Standardise country names

In [87]:
prosperity["Country"] = prosperity["Country"].str.replace("Â", "", regex=False).str.strip()

In [88]:
country_mapping = {
    "Czechia": "Czech Republic",
    "Ireland": "Republic of Ireland"
}

eci["Country"] = eci["Country"].replace(country_mapping)
prosperity["Country"] = prosperity["Country"].replace(country_mapping)
media["Country"] = media["Country"].replace(country_mapping)

### Reslection and Renaming of variables

In [89]:
media = media[[
    "Country",
    "Score"
]]

media = media.rename(columns={
    "Score": "Media_Literacy_Index"
})

In [90]:
print("Display column names:")
print(prosperity.columns)

Display column names:
Index(['Country', 'AveragScore', 'SafetySecurity', 'PersonelFreedom',
       'Governance', 'SocialCapital', 'InvestmentEnvironment',
       'EnterpriseConditions', 'MarketAccessInfrastructure', 'EconomicQuality',
       'LivingConditions', 'Health', 'Education', 'NaturalEnvironment'],
      dtype='object')

In [91]:
prosperity = prosperity[[
    "Country",
    "Governance",
    "SocialCapital",
    "PersonelFreedom",
    "Education"
]]

prosperity = prosperity.rename(columns={
    "PersonelFreedom":"Personal_Freedom",
    "SocialCapital": "Social_Capital"
})

### Checking data types for each dataset

In [92]:
prosperity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           167 non-null    object
 1   Governance        167 non-null    float64
 2   Social_Capital    167 non-null    float64
 3   Personal_Freedom  167 non-null    float64
 4   Education         167 non-null    float64
dtypes: float64(4), object(1)
memory usage: 6.7+ KB

In [93]:
media.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country               41 non-null     object
 1   Media_Literacy_Index  41 non-null     int64
dtypes: int64(1), object(1)
memory usage: 788.0+ bytes

In [94]:

eci.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 729 entries, 0 to 728
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                729 non-null    object
 1   Signatures             729 non-null    int64
 2   Threshold              729 non-null    int64
 3   Percentage             729 non-null    float64
 4   Petition_ID            729 non-null    object
 5   Population             729 non-null    float64
 6   GDP                    729 non-null    float64
 7   Population_Density     729 non-null    int64
 8   Unemployment_Rate      729 non-null    float64
 9   Tertiary_Enrollment    729 non-null    float64
 10  Life_Expectancy        729 non-null    float64
 11  Urban_Population       729 non-null    float64
 12  Labor_Participation    729 non-null    float64
 13  Signatures_Per_Capita  729 non-null    float64
 14  GDP_Per_Capita         729 non-null    float64
 15  Threshold_Ratio        729 non-null    float64
 16  Threshold_Per_Capita   729 non-null    float64
 17  Petition_Name          729 non-null    object
dtypes: float64(12), int64(3), object(3)
memory usage: 102.6+ KB

### Convert to numeric

In [95]:
prosperity.iloc[:,1:] = prosperity.iloc[:,1:].apply(pd.to_numeric)

### Merge datasets

In [96]:
master = eci.merge(
    media,
    on="Country",
    how="left"
)

In [97]:
master = master.merge(
    prosperity,
    on="Country",
    how="left"
)

In [98]:
master = master.merge(
    petition_metadata,
    on="Petition_ID",
    how="left"
)

### Inspection of the merged dataset

### Dataset Shape

In [99]:
master.shape

(729, 29)

### Dataset Info

In [100]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 729 entries, 0 to 728
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                729 non-null    object
 1   Signatures             729 non-null    int64
 2   Threshold              729 non-null    int64
 3   Percentage             729 non-null    float64
 4   Petition_ID            729 non-null    object
 5   Population             729 non-null    float64
 6   GDP                    729 non-null    float64
 7   Population_Density     729 non-null    int64
 8   Unemployment_Rate      729 non-null    float64
 9   Tertiary_Enrollment    729 non-null    float64
 10  Life_Expectancy        729 non-null    float64
 11  Urban_Population       729 non-null    float64
 12  Labor_Participation    729 non-null    float64
 13  Signatures_Per_Capita  729 non-null    float64
 14  GDP_Per_Capita         729 non-null    float64
 15  Threshold_Ratio        729 non-null    float64
 16  Threshold_Per_Capita   729 non-null    float64
 17  Petition_Name_x        729 non-null    object
 18  Media_Literacy_Index   729 non-null    int64
 19  Governance             729 non-null    float64
 20  Social_Capital         729 non-null    float64
 21  Personal_Freedom       729 non-null    float64
 22  Education              729 non-null    float64
 23  Petition_Number        729 non-null    int64
 24  Year                   729 non-null    int64
 25  Petition_Name_y        729 non-null    object
 26  Genre                  729 non-null    object
 27  Total_Signatures       729 non-null    int64
 28  Successful             729 non-null    bool
dtypes: bool(1), float64(16), int64(7), object(5)
memory usage: 160.3+ KB

### Dataset head

In [101]:
master.head()

,Country,Signatures,Threshold,Percentage,Petition_ID,Population,GDP,Population_Density,Unemployment_Rate,Tertiary_Enrollment,...,Governance,Social_Capital,Personal_Freedom,Education,Petition_Number,Year,Petition_Name_y,Genre,Total_Signatures,Successful
0,Austria,10724,13395,80.06,eci_table_01,8877067.0,4.463147e+11,109,4.67,85.1,...,81.19,67.94,85.99,81.93,1,2024,Ban Conversion Practices,Human Rights,1128063,True
1,Belgium,47459,14805,320.56,eci_table_01,11484055.0,5.296067e+11,383,5.59,79.7,...,80.31,64.55,87.70,84.79,1,2024,Ban Conversion Practices,Human Rights,1128063,True
2,Bulgaria,2386,11985,19.91,eci_table_01,6975761.0,8.600000e+10,64,4.34,71.0,...,53.12,54.62,68.31,72.79,1,2024,Ban Conversion Practices,Human Rights,1128063,True
3,Croatia,8574,8460,101.35,eci_table_01,4067500.0,6.041555e+10,73,6.93,67.9,...,56.15,52.19,75.16,73.54,1,2024,Ban Conversion Practices,Human Rights,1128063,True
4,Cyprus,696,4230,16.45,eci_table_01,1198575.0,2.456465e+10,131,7.27,75.9,...,65.69,56.86,78.31,79.14,1,2024,Ban Conversion Practices,Human Rights,1128063,True

### Dataset Column names

In [102]:
master.columns

Index(['Country', 'Signatures', 'Threshold', 'Percentage', 'Petition_ID',
       'Population', 'GDP', 'Population_Density', 'Unemployment_Rate',
       'Tertiary_Enrollment', 'Life_Expectancy', 'Urban_Population',
       'Labor_Participation', 'Signatures_Per_Capita', 'GDP_Per_Capita',
       'Threshold_Ratio', 'Threshold_Per_Capita', 'Petition_Name_x',
       'Media_Literacy_Index', 'Governance', 'Social_Capital',
       'Personal_Freedom', 'Education', 'Petition_Number', 'Year',
       'Petition_Name_y', 'Genre', 'Total_Signatures', 'Successful'],
      dtype='object')

### Checking for missing values

In [103]:
master.isnull().sum()

Country                  0
Signatures               0
Threshold                0
Percentage               0
Petition_ID              0
Population               0
GDP                      0
Population_Density       0
Unemployment_Rate        0
Tertiary_Enrollment      0
Life_Expectancy          0
Urban_Population         0
Labor_Participation      0
Signatures_Per_Capita    0
GDP_Per_Capita           0
Threshold_Ratio          0
Threshold_Per_Capita     0
Petition_Name_x          0
Media_Literacy_Index     0
Governance               0
Social_Capital           0
Personal_Freedom         0
Education                0
Petition_Number          0
Year                     0
Petition_Name_y          0
Genre                    0
Total_Signatures         0
Successful               0
dtype: int64

### Checking for country names based on missing values (incase of name mismatch)

In [104]:
master[master["Media_Literacy_Index"].isna()]["Country"].unique()

array([], dtype=object)

### Checking for duplicates

In [105]:
master.duplicated().sum()

np.int64(0)

### Renaming Columns

In [106]:
master = master.rename(columns={
    "Petition_Name_x": "Petition_Name",
    "Unemployment_Rate": "Unemployment"
})

### Reselection of final variables

In [107]:
master = master[[
    "Petition_ID",
    "Petition_Name",
    "Country",
    "Genre",
    "Year",
    "Total_Signatures",
    "Successful",

    "Signatures",
    "Signatures_Per_Capita",

    "Population",
    "Population_Density",
    "GDP_Per_Capita",
    "Unemployment",
    "Tertiary_Enrollment",
    "Life_Expectancy",

    "Media_Literacy_Index",

    "Governance",
    "Social_Capital",
    "Personal_Freedom",
    "Education"
]]

### Final Inspection

In [108]:
master.head()

,Petition_ID,Petition_Name,Country,Genre,Year,Total_Signatures,Successful,Signatures,Signatures_Per_Capita,Population,Population_Density,GDP_Per_Capita,Unemployment,Tertiary_Enrollment,Life_Expectancy,Media_Literacy_Index,Governance,Social_Capital,Personal_Freedom,Education
0,eci_table_01,Ban Conversion Practices,Austria,Human Rights,2024,1128063,True,10724,0.001208,8877067.0,109,50277.275087,4.67,85.1,81.6,59,81.19,67.94,85.99,81.93
1,eci_table_01,Ban Conversion Practices,Belgium,Human Rights,2024,1128063,True,47459,0.004133,11484055.0,383,46116.699234,5.59,79.7,81.6,61,80.31,64.55,87.70,84.79
2,eci_table_01,Ban Conversion Practices,Bulgaria,Human Rights,2024,1128063,True,2386,0.000342,6975761.0,64,12328.404026,4.34,71.0,74.9,31,53.12,54.62,68.31,72.79
3,eci_table_01,Ban Conversion Practices,Croatia,Human Rights,2024,1128063,True,8574,0.002108,4067500.0,73,14853.239837,6.93,67.9,78.1,45,56.15,52.19,75.16,73.54
4,eci_table_01,Ban Conversion Practices,Cyprus,Human Rights,2024,1128063,True,696,0.000581,1198575.0,131,20494.877613,7.27,75.9,80.8,39,65.69,56.86,78.31,79.14

In [109]:
master.shape

(729, 20)

### Export to CSV file

In [110]:
master.to_csv("C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Dissertation/MSc-Dissertation/data/Prepared Datasets/master_dataset.csv", index=False) # https://www.geeksforgeeks.org/pandas/saving-a-pandas-dataframe-as-a-csv/

print("Cleaned dataset has been saved as 'master_dataset.csv'.")

Cleaned dataset has been saved as 'master_dataset.csv'.

### Secondary master dataset with only successful ECIs

In [111]:
successful_master = master[master["Successful"] == True].copy()

In [112]:
successful_master.head()

,Petition_ID,Petition_Name,Country,Genre,Year,Total_Signatures,Successful,Signatures,Signatures_Per_Capita,Population,Population_Density,GDP_Per_Capita,Unemployment,Tertiary_Enrollment,Life_Expectancy,Media_Literacy_Index,Governance,Social_Capital,Personal_Freedom,Education
0,eci_table_01,Ban Conversion Practices,Austria,Human Rights,2024,1128063,True,10724,0.001208,8877067.0,109,50277.275087,4.67,85.1,81.6,59,81.19,67.94,85.99,81.93
1,eci_table_01,Ban Conversion Practices,Belgium,Human Rights,2024,1128063,True,47459,0.004133,11484055.0,383,46116.699234,5.59,79.7,81.6,61,80.31,64.55,87.70,84.79
2,eci_table_01,Ban Conversion Practices,Bulgaria,Human Rights,2024,1128063,True,2386,0.000342,6975761.0,64,12328.404026,4.34,71.0,74.9,31,53.12,54.62,68.31,72.79
3,eci_table_01,Ban Conversion Practices,Croatia,Human Rights,2024,1128063,True,8574,0.002108,4067500.0,73,14853.239837,6.93,67.9,78.1,45,56.15,52.19,75.16,73.54
4,eci_table_01,Ban Conversion Practices,Cyprus,Human Rights,2024,1128063,True,696,0.000581,1198575.0,131,20494.877613,7.27,75.9,80.8,39,65.69,56.86,78.31,79.14

In [113]:
successful_master.to_csv("C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Dissertation/MSc-Dissertation/data/Prepared Datasets/successful_master_dataset.csv", index=False) # https://www.geeksforgeeks.org/pandas/saving-a-pandas-dataframe-as-a-csv/

print("Cleaned dataset has been saved as 'successful_master_dataset.csv'.")

Cleaned dataset has been saved as 'successful_master_dataset.csv'.