### Matthew Riddell 
### D00245674
### MSc in Data Analytics
### Dissertation
### Data Prepartation Jupyter Notebook

In [24]:
import pandas as pd 
import numpy as np
import os

#### File path and file loading

In [25]:
file_path = r"C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Dissertation/MSc-Dissertation/data/Unprepared Datasets/"

# world stats datasets
file_name_worldstat = "world-data-2023.csv"

# eci datasets
eci_files = [
    "eci_table_01.csv",
    "eci_table_02.csv",
    "eci_table_04.csv",
    "eci_table_06.csv",
    "eci_table_07.csv"
]

### Loading World stats dataset

In [26]:
file_path_worldstat = os.path.join(file_path, file_name_worldstat)
world_data = pd.read_csv(file_path_worldstat)

### Loading ECI datasets into one dataset
This combines the data from all selected petitions into one dataset while creating a petition id to differentiate

In [27]:
eci_dfs = []
petition_totals = []

for file_name in eci_files:
    
    file_path_eci = os.path.join(file_path, file_name)
    
    df = pd.read_csv(file_path_eci)
    
    # Add id for each petition
    df["petition_id"] = file_name.replace(".csv", "")
    
    eci_dfs.append(df)

# Combine into one dataset
eci_data = pd.concat(eci_dfs, ignore_index=True)

#### Display first 5 rows

In [28]:
eci_data.head(40)

                        Country Signatures Threshold Percentage   petition_id
0                       Austria     10,724    13,395     80.06%  eci_table_01
1                       Belgium     47,459    14,805    320.56%  eci_table_01
2                      Bulgaria      2,386    11,985     19.91%  eci_table_01
3                       Croatia      8,574     8,460    101.35%  eci_table_01
4                        Cyprus        696     4,230     16.45%  eci_table_01
5                       Czechia      3,774    14,805     25.49%  eci_table_01
6                       Denmark      8,587     9,870     87.00%  eci_table_01
7                       Estonia      1,519     4,935     30.78%  eci_table_01
8                       Finland     23,618     9,870    239.29%  eci_table_01
9                        France    580,568    55,695  1,042.41%  eci_table_01
10                      Germany     92,739    67,680    137.03%  eci_table_01
11                       Greece      4,127    14,805     27.88%  eci_table_01
12                      Hungary      3,195    14,805     21.58%  eci_table_01
13                      Ireland     18,503     9,165    201.89%  eci_table_01
14                        Italy     60,701    53,580    113.29%  eci_table_01
15                       Latvia      1,103     5,640     19.56%  eci_table_01
16                    Lithuania      1,973     7,755     25.44%  eci_table_01
17                   Luxembourg      2,091     4,230     49.43%  eci_table_01
18                        Malta        861     4,230     20.35%  eci_table_01
19                  Netherlands     38,112    20,445    186.41%  eci_table_01
20                       Poland      9,039    36,660     24.66%  eci_table_01
21                     Portugal      9,025    14,805     60.96%  eci_table_01
22                      Romania      9,932    23,265     42.69%  eci_table_01
23                     Slovakia      2,671     9,870     27.06%  eci_table_01
24                     Slovenia      6,400     5,640    113.48%  eci_table_01
25                        Spain    162,018    41,595    389.51%  eci_table_01
26                       Sweden     17,668    14,805    119.34%  eci_table_01
27  Total number of signatories  1,128,063       NaN        NaN  eci_table_01
28                      Austria        109    13,395      0.81%  eci_table_02
29                      Belgium        160    14,805      1.08%  eci_table_02
30                     Bulgaria         47    11,985      0.39%  eci_table_02
31                      Croatia         76     8,460      0.90%  eci_table_02
32                       Cyprus         27     4,230      0.64%  eci_table_02
33                      Czechia         39    14,805      0.26%  eci_table_02
34                      Denmark         29     9,870      0.29%  eci_table_02
35                      Estonia         18     4,935      0.36%  eci_table_02
36                      Finland        102     9,870      1.03%  eci_table_02
37                       France        361    55,695      0.65%  eci_table_02
38                      Germany        302    67,680      0.45%  eci_table_02
39                       Greece        120    14,805      0.81%  eci_table_02

In [29]:
world_data.head(5)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887

In [30]:
print("First 5 rows of the ECI data:")
print(eci_data.head())

First 5 rows of the ECI data:
    Country Signatures Threshold Percentage   petition_id
0   Austria     10,724    13,395     80.06%  eci_table_01
1   Belgium     47,459    14,805    320.56%  eci_table_01
2  Bulgaria      2,386    11,985     19.91%  eci_table_01
3   Croatia      8,574     8,460    101.35%  eci_table_01
4    Cyprus        696     4,230     16.45%  eci_table_01

In [31]:
print("First 5 rows of the World Stat dataset:")
print(world_data.head())

First 5 rows of the World Stat dataset:
       Country Density\n(P/Km2) Abbreviation Agricultural Land( %)  \
0  Afghanistan               60           AF                58.10%
1      Albania              105           AL                43.10%
2      Algeria               18           DZ                17.40%
3      Andorra              164           AD                40.00%
4       Angola               26           AO                47.50%

  Land Area(Km2) Armed Forces size  Birth Rate  Calling Code  \
0        652,230           323,000       32.49          93.0
1         28,748             9,000       11.78         355.0
2      2,381,741           317,000       24.28         213.0
3            468               NaN        7.20         376.0
4      1,246,700           117,000       40.73         244.0

  Capital/Major City Co2-Emissions  ... Out of pocket health expenditure  \
0              Kabul         8,672  ...                           78.40%
1             Tirana         4,536  ...                           56.90%
2            Algiers       150,006  ...                           28.10%
3   Andorra la Vella           469  ...                           36.40%
4             Luanda        34,693  ...                           33.40%

  Physicians per thousand  Population  \
0                    0.28  38,041,754
1                    1.20   2,854,191
2                    1.72  43,053,054
3                    3.33      77,142
4                    0.21  31,825,295

   Population: Labor force participation (%) Tax revenue (%) Total tax rate  \
0                                     48.90%           9.30%         71.40%
1                                     55.70%          18.60%         36.60%
2                                     41.20%          37.20%         66.10%
3                                        NaN             NaN            NaN
4                                     77.50%           9.20%         49.10%

  Unemployment rate Urban_population   Latitude  Longitude
0            11.12%        9,797,273  33.939110  67.709953
1            12.33%        1,747,593  41.153332  20.168331
2            11.70%       31,510,100  28.033886   1.659626
3               NaN           67,873  42.506285   1.521801
4             6.89%       21,061,025 -11.202692  17.873887

[5 rows x 35 columns]

#### Check basic information about the dataset

In [32]:
print("Information about the ECI dataset:")
print(eci_data.info())

Information about the ECI dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Country      140 non-null    object
 1   Signatures   140 non-null    object
 2   Threshold    135 non-null    object
 3   Percentage   135 non-null    object
 4   petition_id  140 non-null    object
dtypes: object(5)
memory usage: 5.6+ KB
None

In [33]:
print("Information about the World Data dataset:")
print(world_data.info())

Information about the World Data dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Country                                    195 non-null    object
 1   Density
(P/Km2)                            195 non-null    object
 2   Abbreviation                               188 non-null    object
 3   Agricultural Land( %)                      188 non-null    object
 4   Land Area(Km2)                             194 non-null    object
 5   Armed Forces size                          171 non-null    object
 6   Birth Rate                                 189 non-null    float64
 7   Calling Code                               194 non-null    float64
 8   Capital/Major City                         192 non-null    object
 9   Co2-Emissions                              188 non-null    object
 10  CPI                                        178 non-null    object
 11  CPI Change (%)                             179 non-null    object
 12  Currency-Code                              180 non-null    object
 13  Fertility Rate                             188 non-null    float64
 14  Forested Area (%)                          188 non-null    object
 15  Gasoline Price                             175 non-null    object
 16  GDP                                        193 non-null    object
 17  Gross primary education enrollment (%)     188 non-null    object
 18  Gross tertiary education enrollment (%)    183 non-null    object
 19  Infant mortality                           189 non-null    float64
 20  Largest city                               189 non-null    object
 21  Life expectancy                            187 non-null    float64
 22  Maternal mortality ratio                   181 non-null    float64
 23  Minimum wage                               150 non-null    object
 24  Official language                          190 non-null    object
 25  Out of pocket health expenditure           188 non-null    object
 26  Physicians per thousand                    188 non-null    float64
 27  Population                                 194 non-null    object
 28  Population: Labor force participation (%)  176 non-null    object
 29  Tax revenue (%)                            169 non-null    object
 30  Total tax rate                             183 non-null    object
 31  Unemployment rate                          176 non-null    object
 32  Urban_population                           190 non-null    object
 33  Latitude                                   194 non-null    float64
 34  Longitude                                  194 non-null    float64
dtypes: float64(9), object(26)
memory usage: 53.4+ KB
None

#### Display column names

In [34]:
print("Original column names:")
print(eci_data.columns)

Original column names:
Index(['Country', 'Signatures', 'Threshold', 'Percentage', 'petition_id'], dtype='object')

In [35]:
print("Original column names:")
print(world_data.columns)

Original column names:
Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price', 'GDP', 'Gross primary education enrollment (%)',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Largest city', 'Life expectancy', 'Maternal mortality ratio',
       'Minimum wage', 'Official language', 'Out of pocket health expenditure',
       'Physicians per thousand', 'Population',
       'Population: Labor force participation (%)', 'Tax revenue (%)',
       'Total tax rate', 'Unemployment rate', 'Urban_population', 'Latitude',
       'Longitude'],
      dtype='object')

## Data Cleaning

### Remove total signatures rows from the dataset

checks every row to see if there is a value contained in the country column, total signatures row doesnt contain a value there so it is NaN 

it then excludes it from the dataset

In [36]:
eci_data = eci_data[
    ~eci_data["Country"].str.contains(
        "Total number of signatories",
        case=False,
        na=False
    )
]

### Remove Sponsor and Metadata rows

In [37]:
eci_data = eci_data[
    ~eci_data["Country"].str.contains(
        "Name of sponsor|Date|Description",
        case=False,
        na=False
    )
]

### Removing commas from numeric columns

#### Signatures column

In [38]:
eci_data["Signatures"] = (
    eci_data["Signatures"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

#### Threshold Column

In [39]:
eci_data["Threshold"] = (
    eci_data["Threshold"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

#### Percentage Column

In [40]:
eci_data["Percentage"] = (
    eci_data["Percentage"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

### Remove Percentage Sign from Percentage column

In [41]:
eci_data["Percentage"] = (
    eci_data["Percentage"]
    .astype(str)
    .str.replace("%", "", regex=False)
)

### Convert columns into numeric

#### Signatures column

In [42]:
eci_data["Signatures"] = pd.to_numeric(
    eci_data["Signatures"],
    errors="coerce"
)

#### Threshold Column

In [43]:
eci_data["Threshold"] = pd.to_numeric(
    eci_data["Threshold"],
    errors="coerce"
)

#### Percentage Column

In [44]:
eci_data["Percentage"] = pd.to_numeric(
    eci_data["Percentage"],
    errors="coerce"
)

### Checking the data after cleaning the columns and converting into numericals

In [45]:
eci_data.head(30)

        Country  Signatures  Threshold  Percentage   petition_id
0       Austria       10724      13395       80.06  eci_table_01
1       Belgium       47459      14805      320.56  eci_table_01
2      Bulgaria        2386      11985       19.91  eci_table_01
3       Croatia        8574       8460      101.35  eci_table_01
4        Cyprus         696       4230       16.45  eci_table_01
5       Czechia        3774      14805       25.49  eci_table_01
6       Denmark        8587       9870       87.00  eci_table_01
7       Estonia        1519       4935       30.78  eci_table_01
8       Finland       23618       9870      239.29  eci_table_01
9        France      580568      55695     1042.41  eci_table_01
10      Germany       92739      67680      137.03  eci_table_01
11       Greece        4127      14805       27.88  eci_table_01
12      Hungary        3195      14805       21.58  eci_table_01
13      Ireland       18503       9165      201.89  eci_table_01
14        Italy       60701      53580      113.29  eci_table_01
15       Latvia        1103       5640       19.56  eci_table_01
16    Lithuania        1973       7755       25.44  eci_table_01
17   Luxembourg        2091       4230       49.43  eci_table_01
18        Malta         861       4230       20.35  eci_table_01
19  Netherlands       38112      20445      186.41  eci_table_01
20       Poland        9039      36660       24.66  eci_table_01
21     Portugal        9025      14805       60.96  eci_table_01
22      Romania        9932      23265       42.69  eci_table_01
23     Slovakia        2671       9870       27.06  eci_table_01
24     Slovenia        6400       5640      113.48  eci_table_01
25        Spain      162018      41595      389.51  eci_table_01
26       Sweden       17668      14805      119.34  eci_table_01
28      Austria         109      13395        0.81  eci_table_02
29      Belgium         160      14805        1.08  eci_table_02
30     Bulgaria          47      11985        0.39  eci_table_02

### Standardise country names

this is so they match the country names in the world dataset

In [47]:
country_mapping = {
    "Czechia": "Czech Republic",
    "Ireland": "Republic of Ireland"
}

eci_data["Country"] = eci_data["Country"].replace(country_mapping)

### Checking the data after cleaning the columns and converting into numericals

In [48]:
eci_data.head(30)

                Country  Signatures  Threshold  Percentage   petition_id
0               Austria       10724      13395       80.06  eci_table_01
1               Belgium       47459      14805      320.56  eci_table_01
2              Bulgaria        2386      11985       19.91  eci_table_01
3               Croatia        8574       8460      101.35  eci_table_01
4                Cyprus         696       4230       16.45  eci_table_01
5        Czech Republic        3774      14805       25.49  eci_table_01
6               Denmark        8587       9870       87.00  eci_table_01
7               Estonia        1519       4935       30.78  eci_table_01
8               Finland       23618       9870      239.29  eci_table_01
9                France      580568      55695     1042.41  eci_table_01
10              Germany       92739      67680      137.03  eci_table_01
11               Greece        4127      14805       27.88  eci_table_01
12              Hungary        3195      14805       21.58  eci_table_01
13  Republic of Ireland       18503       9165      201.89  eci_table_01
14                Italy       60701      53580      113.29  eci_table_01
15               Latvia        1103       5640       19.56  eci_table_01
16            Lithuania        1973       7755       25.44  eci_table_01
17           Luxembourg        2091       4230       49.43  eci_table_01
18                Malta         861       4230       20.35  eci_table_01
19          Netherlands       38112      20445      186.41  eci_table_01
20               Poland        9039      36660       24.66  eci_table_01
21             Portugal        9025      14805       60.96  eci_table_01
22              Romania        9932      23265       42.69  eci_table_01
23             Slovakia        2671       9870       27.06  eci_table_01
24             Slovenia        6400       5640      113.48  eci_table_01
25                Spain      162018      41595      389.51  eci_table_01
26               Sweden       17668      14805      119.34  eci_table_01
28              Austria         109      13395        0.81  eci_table_02
29              Belgium         160      14805        1.08  eci_table_02
30             Bulgaria          47      11985        0.39  eci_table_02