### Matthew Riddell 
### D00245674
### MSc in Data Analytics
### Dissertation
### Data Exploration Jupyter Notebook

Data Exploration conducted before Data Preparation and Cleaning

In [1]:
import pandas as pd 
import numpy as np

#### File path and file loading

In [5]:
file_path = "C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Dissertation/MSc-Dissertation/data/Unprepared Datasets/"
file_name_worldstat = "world-data-2023.csv"
file_name_eci = "eci_table_01.csv"

file_path_worldstat = file_path + file_name_worldstat
file_path_eci = file_path + file_name_eci

In [6]:
worldstat_data = pd.read_csv(file_path_worldstat)

In [7]:
eci_data = pd.read_csv(file_path_eci)

#### Display first 5 rows

In [8]:
eci_data.head(5)

    Country Statements of support Threshold Percentage
0   Austria                20,714    13,395    154.64%
1   Belgium                31,846    14,805    215.10%
2  Bulgaria                14,238    11,985    118.80%
3   Croatia                14,403     8,460    170.25%
4    Cyprus                 1,997     4,230     47.21%

In [9]:
worldstat_data.head(5)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887

In [11]:
print("First 5 rows of the ECI data:")
print(eci_data.head())

First 5 rows of the ECI data:
    Country Statements of support Threshold Percentage
0   Austria                20,714    13,395    154.64%
1   Belgium                31,846    14,805    215.10%
2  Bulgaria                14,238    11,985    118.80%
3   Croatia                14,403     8,460    170.25%
4    Cyprus                 1,997     4,230     47.21%

In [12]:
print("First 5 rows of the World Stat dataset:")
print(worldstat_data.head())

First 5 rows of the World Stat dataset:
       Country Density\n(P/Km2) Abbreviation Agricultural Land( %)  \
0  Afghanistan               60           AF                58.10%
1      Albania              105           AL                43.10%
2      Algeria               18           DZ                17.40%
3      Andorra              164           AD                40.00%
4       Angola               26           AO                47.50%

  Land Area(Km2) Armed Forces size  Birth Rate  Calling Code  \
0        652,230           323,000       32.49          93.0
1         28,748             9,000       11.78         355.0
2      2,381,741           317,000       24.28         213.0
3            468               NaN        7.20         376.0
4      1,246,700           117,000       40.73         244.0

  Capital/Major City Co2-Emissions  ... Out of pocket health expenditure  \
0              Kabul         8,672  ...                           78.40%
1             Tirana         4,536  ...                           56.90%
2            Algiers       150,006  ...                           28.10%
3   Andorra la Vella           469  ...                           36.40%
4             Luanda        34,693  ...                           33.40%

  Physicians per thousand  Population  \
0                    0.28  38,041,754
1                    1.20   2,854,191
2                    1.72  43,053,054
3                    3.33      77,142
4                    0.21  31,825,295

   Population: Labor force participation (%) Tax revenue (%) Total tax rate  \
0                                     48.90%           9.30%         71.40%
1                                     55.70%          18.60%         36.60%
2                                     41.20%          37.20%         66.10%
3                                        NaN             NaN            NaN
4                                     77.50%           9.20%         49.10%

  Unemployment rate Urban_population   Latitude  Longitude
0            11.12%        9,797,273  33.939110  67.709953
1            12.33%        1,747,593  41.153332  20.168331
2            11.70%       31,510,100  28.033886   1.659626
3               NaN           67,873  42.506285   1.521801
4             6.89%       21,061,025 -11.202692  17.873887

[5 rows x 35 columns]

#### Check basic information about the dataset

In [13]:
print("Information about the dataset:")
print(eci_data.info())

Information about the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                32 non-null     object
 1   Statements of support  32 non-null     object
 2   Threshold              31 non-null     object
 3   Percentage             27 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB
None

In [14]:
print("Information about the dataset:")
print(worldstat_data.info())

Information about the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Country                                    195 non-null    object
 1   Density
(P/Km2)                            195 non-null    object
 2   Abbreviation                               188 non-null    object
 3   Agricultural Land( %)                      188 non-null    object
 4   Land Area(Km2)                             194 non-null    object
 5   Armed Forces size                          171 non-null    object
 6   Birth Rate                                 189 non-null    float64
 7   Calling Code                               194 non-null    float64
 8   Capital/Major City                         192 non-null    object
 9   Co2-Emissions                              188 non-null    object
 10  CPI                                        178 non-null    object
 11  CPI Change (%)                             179 non-null    object
 12  Currency-Code                              180 non-null    object
 13  Fertility Rate                             188 non-null    float64
 14  Forested Area (%)                          188 non-null    object
 15  Gasoline Price                             175 non-null    object
 16  GDP                                        193 non-null    object
 17  Gross primary education enrollment (%)     188 non-null    object
 18  Gross tertiary education enrollment (%)    183 non-null    object
 19  Infant mortality                           189 non-null    float64
 20  Largest city                               189 non-null    object
 21  Life expectancy                            187 non-null    float64
 22  Maternal mortality ratio                   181 non-null    float64
 23  Minimum wage                               150 non-null    object
 24  Official language                          190 non-null    object
 25  Out of pocket health expenditure           188 non-null    object
 26  Physicians per thousand                    188 non-null    float64
 27  Population                                 194 non-null    object
 28  Population: Labor force participation (%)  176 non-null    object
 29  Tax revenue (%)                            169 non-null    object
 30  Total tax rate                             183 non-null    object
 31  Unemployment rate                          176 non-null    object
 32  Urban_population                           190 non-null    object
 33  Latitude                                   194 non-null    float64
 34  Longitude                                  194 non-null    float64
dtypes: float64(9), object(26)
memory usage: 53.4+ KB
None

#### Display column names

In [15]:
print("Original column names:")
print(eci_data.columns)

Original column names:
Index(['Country', 'Statements of support', 'Threshold', 'Percentage'], dtype='object')

In [16]:
print("Original column names:")
print(worldstat_data.columns)

Original column names:
Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price', 'GDP', 'Gross primary education enrollment (%)',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Largest city', 'Life expectancy', 'Maternal mortality ratio',
       'Minimum wage', 'Official language', 'Out of pocket health expenditure',
       'Physicians per thousand', 'Population',
       'Population: Labor force participation (%)', 'Tax revenue (%)',
       'Total tax rate', 'Unemployment rate', 'Urban_population', 'Latitude',
       'Longitude'],
      dtype='object')